### ISSUE TITLE
styles not working- missing gridster-item-inner 

### ISSUE THREAD

**Issue by ash2014** [swiety85/angular2gridster#102]
I installed gridster2 as npm module for my angular4 application. The panel looks borderless. I compared my page with the demo and found that I am missing some styles classes. When I inspect my page i dont see gridster-item-inner class. This library is listed under /node_modules and the styles are inline. Are there any other steps to add the css classes when installed through npm ? I have attached a screenshot of my page. 
Anyone seen this issue ?  

<img width="1303" alt="screen shot 2017-09-27 at 11 05 59 pm" src="https://user-images.githubusercontent.com/7330946/30951591-b7bed9b8-a3d8-11e7-8671-c3179d1256a3.png">

**Comment by swiety85** [comment]
Hi, the library has build in css only for core structure (no borders, backgrounds etc.). It's on you to style it like you want. 
The styles of demo page you can find in [styles.css](https://github.com/swiety85/angular2gridster/blob/master/demo/src/styles.css) of demo source.
In case of any more questions, ask.

**Comment by ash2014** [comment]
Thanks I will try that. gridster-inner-item class is added by the core gridster library so ideally the core css should handle it ?

**Comment by swiety85** [comment]
It's good point and I will update Wiki with info about applying styles for Gridster components, but I will not include any additional "theme" css to gridster-inner-item class out of the box.

**Comment by ash2014** [comment]
gridster-inner-item out of the box can atleast have the borders. Users can always override it to customize.

**Comment by danailvidev** [comment]
I have same problem . Copied all html,css + .ts and can't get desired demo result

**Comment by swiety85** [comment]
Hi, from which to which file exactly you copy CSS?

**Comment by danailvidev** [comment]
Hello, thank you for the fast answer. First ive tried with this  [app.component.css](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.css) then with this [style.ss](https://github.com/swiety85/angular2gridster/blob/master/demo/src/styles.css)
