### ISSUE TITLE
gridster-item should automatically accommodate  over empty place

### ISSUE THREAD

**Issue by DinkuMM** [swiety85/angular2gridster#11]
while adding new gridster-item we have to pass its x and y potion. is there anyway to not pass it and it should dynamically adjust it self to empty place.

**Comment by swiety85** [comment]
This is good point. I will implement it as you wrote in very next step. 
In meanwhile you can try to use new feature that will be soon available: adding widgets by dragging from outside. I will try to provide new release in following week.

**Comment by DinkuMM** [comment]
@swiety85 thanks for the replay. Can i know the date of next release which will include of this bug and new drag feature too ?.

**Comment by swiety85** [comment]
Yep, today - v. 0.4.0.
Don't hesitate to write in case of any new issues, suggestions or wishes.
Have fun! :-)

**Comment by DinkuMM** [comment]
HI i am not able to install 'angular2gridster' from NPM. Its giving following error.

**Comment by DinkuMM** [comment]
its only working when i have manually copied the source from your demo

**Comment by HamzaDevz** [comment]
Hi, any news about setting x, y position ?

**Comment by swiety85** [comment]
I'm almost done with new resizing feature. This issue will be next.
You can track progress on [this board](https://github.com/swiety85/angular2gridster/projects/1).

**Comment by swiety85** [comment]
This feature was provided in v. 0.5.0. Please check. I will appreciate any feedback.

**Comment by swiety85** [comment]
Because of bug in build code in v. 0.5.0 this feature could not work, but in 0.5.1 it's fixed and should work as expected.
