### ISSUE TITLE
How can we get positions of widget?

### ISSUE THREAD

**Issue by anushamramyam** [swiety85/angular2gridster#110]
Hi,
  In our project we are using angular2gridster. According to requirement we have list of components which are draggable. For those components we are using gridster to re arrange and resize.I have  created one object with widget coordinates. like as below
var widget = {'x':0,'y':0,'w':1,'h':1}
I had put this widget object inside the main component object .this main component object have the details of which type of component and datatype etc,. on each drag and drop the coordinates of widget are same since I had put widget object in main component object. Since I have given width for each component so the widgets are not overlapping, but the coordinates are {'x':0,'y':0,'w':1,'h':1} .Now the problem is, on  onChange() we can get positions of widgets but  on drag and drop how can we get positions of widget?

Can you please help me. Thanks in advance

**Comment by swiety85** [comment]
For changing `x`, `y`, `w` and `h` you can use `change` event on GridsterItem:
```html
<gridster-item (change)="itemChange($event)" [x]="widget.x" [y]="widget.y" ...>
...
</gridster-item>
```
Second approach is using two way binding:
```html
<gridster-item [(x)]="widget.x" [(y)]="widget.y" [(w)]="widget.w" [(h)]="widget.h">
...
</gridster-item>
```
In this case these properties will be updated on drop out of the box.
More info you can find in More info about `$event` object you can find in [wiki](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#gridsteritemcomponent).
I hope answered your question.

**Comment by anushamramyam** [comment]
Hello Sir,

What you said is absolutely right. According to project requirement we have few components which are draggable. for that we have used other library. onDropSuccess($event) we have some logic  to perform like what type of input, datatype, etc,.What I am doing is onDropSuccess($event) I am attaching this object  {'x':0,'y':0,'w':1,'h':1}. So on every drag and drop the each component have same coordinates. I have tried with  < .... gridsterItemPrototype   (drop)="addWidget($event)" >
but this $event has no information about coordinates. I want  to get actual coordinates on drag and drop of component.

I have attached screenshot for your reference
![gridview](https://user-images.githubusercontent.com/31650367/31423151-81596490-ae70-11e7-98f7-c22a1423609b.png)

**Comment by swiety85** [comment]
For dragging new items from outside you can use `gridsterItemPrototype` like you wrote. The $event object for `drop` from this directive will have `item` and `gridster`properties. More info [here](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#gridsteritemprototypedirective).
Have a look how adding widget on drop is done in [demo page](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.ts#L148):
```js
    addWidgetFromDrag(gridster: GridsterComponent, event: any) {
        const item = event.item;
        this.widgets.push({
            x: item.x, y: item.y, w: item.w, h: item.h
        });
        console.log('add widget from drag to:', gridster);
    }
```
