### ISSUE TITLE
Scrolling not working on Android devices

### ISSUE THREAD

**Issue by AlMuIssues** [swiety85/angular2gridster#111]
I use angular2gridster in my dashboard and it works fine. But with the newest version ( 0.6.7 ) I habe a problem only on android smartphone ( PC and iOS devices work fine). I can't scroll my dashboard. If I go back to 0.6.6 than everything works fine. Do you habe any Idea? Some scroll event changes in new version?

angular/animations: "^4.4.4",
angular/common: "^4.4.4",
angular/compiler: "^4.4.4",
angular/core: "^4.4.4",
angular/forms: "^4.4.4",
angular/http: "^4.4.4",
angular/platform-browser: "^4.4.4",
angular/platform-browser-dynamic: "^4.4.4",
angular/router: "^4.4.4",
angular2gridster: "^0.6.7",
core-js: "^2.5.1",
rxjs: "^5.4.2",
zone.js: "^0.8.18"
angular/cli: ^1.4.5

**Comment by swiety85** [comment]
Fix in v.0.6.8.
