### ISSUE TITLE
Is there any way to do on widget resize input elements which are inside the widget also should resize.

### ISSUE THREAD

**Issue by anushamramyam** [swiety85/angular2gridster#112]
Hi,

Is there any solution or way to do, on  widget resize input elements(input,textarea, etc,.) which are inside the widget also should resize.
for Example on increase of widget width input element also should grow and on decrease of widget width input element should shrink.

I have attached screenshot for reference.
![gridview](https://user-images.githubusercontent.com/31650367/31387766-31229096-ade9-11e7-8baf-88d9533ab553.png)

Thanks in advance

**Comment by swiety85** [comment]
Hi, if I understand you right, you want to fit width of form fields to widget size. In this case it should be enough to set relative size in width css property e.g. `width: 100%;` (and on every container up to `.gridster-item-inner`).

**Comment by anushamramyam** [comment]
Hello Sir,

 I have fixed this issue. Thank you
