### ISSUE TITLE
Cannot read property 'reload' of undefined

### ISSUE THREAD

**Issue by anushamramyam** [swiety85/angular2gridster#113]
HI,
     I have two tabs in my project, I have different instances of gridster  in each tab.In first tab what ever the changes made to the widgets I am saving in to one object. In second tab I am trying to render with that object,, but not rendering properly. so I have used this.gridster.reload(). It is giving console error "Cannot read property 'reload' of undefined". Since gridster object is undefined.
I have used the below statements 
import { GridsterComponent } from 'angular2gridster';
@ViewChild(GridsterComponent) gridster: GridsterComponent;
this.gridster.reload();

Am I missing anything?

Thanks in advance.

**Comment by swiety85** [comment]
_"In second tab I am trying to render with that object,, but not rendering properly. so I have used this.gridster.reload()."_ - I'm not sure what you mean.
Maybe some code would help me to understand the problem. Send me please part of component class and html related with your problem.

**Comment by anushamramyam** [comment]
Thank you for your reply.
In my case two tabs means, first tab is for configuration of widgets.second tab is for preview.
The code for configuration tab is

config.html
...........................

<gridster [options]="gridsterOptions"  id="chartLocation" *ngIf="!loadingChart" >
       <div [dropZones]="['components']" dnd-droppable (onDropSuccess)="OnDropcomponent($event);" style="height:400px;width:100%;padding:5px;overflow: auto;">
       <gridster-item class="col-lg-3 col-sm-4 " *ngFor="let fields of formBuilderMetadata;let widget of widgets; let id=index;" (change)="itemChanged($event,id)"  
[x]="widget.x" [y]="widget.y" [w]="widget.w" [h]="widget.h">
               ...............
</gridster-item>
</div>
</gridster >
-------------------------------------------------------------------------------------------------------------
config.ts

 widgetConfig = {
         x: 0, y: 0,
         w: 1, h: 1,
        dragAndDrop :true
    }

 //Function to create component on drag-drop from component list
    public OnDropcomponent(event) {
        var formObj = new FormComponentsObject;
        formObj.type = (event.dragData.label);
        ....................
        formObj.widget = this.widgetConfig;
        this.formBuilderMetadata.push(formObj);
    }
------------------------------------------------------------------------------------------------------------------
In second tab that is preview I am trying to render the formBuilderMetadata which is saved in config.ts.

preview.ts

import { FormBuilderPrepareData } from './../../util/FormBuilderPrepareData.component';
import { ViewChild } from '@angular/core';
import { GridsterComponent } from 'angular2gridster';
export class FormBuilderComponent implements OnInit, OnChanges {
@ViewChild(GridsterComponent) gridster: GridsterComponent;

ngOnChanges() {
this.widgets = [];
// Sort formBuilderMetadata by its coordinates Y and X
this.formBuilderMetadata.sort(function(a,b) {
if ( a.widget.y > b.widget.y)
return 1;
else if ( a.widget.y < b.widget.y)
return -1;
else if (a.widget.x > b.widget.x )
return 1;
else if ( a.widget.x < b.widget.x)
return -1;
else
return 0;
})
this.gridster.reload();
}
}
-------------------------------------------------------------------------------------------------------------
preview.html

<gridster [options]="gridsterOptions"  id="chartLocation" *ngIf="!loadingChart" >
                    <div style="height:400px;width:100%;padding:5px;overflow: auto;">
                            <gridster-item class="col-lg-3 col-sm-4 " *ngFor="let fields of formBuilderMetadata;let widget of widgets; let id=index"
                            [x]="widget.x" [y]="widget.y" [w]="widget.w" [h]="widget.h">
</gridster-item>
</div>
</gridster>

**Comment by meyer20** [comment]
Hi @anushamramyam I'm having the same problem, have you been able to fix the error?
![er](https://user-images.githubusercontent.com/13800506/42295062-f69b5358-7fbc-11e8-9b48-3cb63b8f76b4.PNG)

**Comment by anushamramyam** [comment]
Hi @meyer20 ,

I have fixed this issue with reload() and working absolutely fine.
