### ISSUE TITLE
Read position disorderly

### ISSUE THREAD

**Issue by menme95** [swiety85/angular2gridster#119]
I have a JSON from which I read the positions of gridster items, but they have messy positions. 
At first I don't have any problema, but if I resize the window, the items are placed radomly.

On the other hand, I tested my web in firefox and the second line was above the first, but if you make any change it is fixed.

**Comment by swiety85** [comment]
Hi, sorray but I don't get your explanation. Could you given me some code example (HTML and JS)?
Do you have responsiveOptions set?
