### ISSUE TITLE
How can I use the library with webpack?

### ISSUE THREAD

**Issue by dedalusmax** [swiety85/angular2gridster#12]
I included this line in vendor.ts after installing:

import 'angular2gridster';

but,webpack dev server throws me myriads of error like:

ERROR in [default] ...\node_modules\angular2gridster\src\gridster.service.ts:298:38 
Parameter 'item' implicitly has an 'any' type.

**Comment by dedalusmax** [comment]
btw, I found out that the tslint throws that error. I even fixed that in your files locally, and now the webpack compiles, but the application throws me this exception:

Error: Unexpected value 'GridsterModule' imported by the module 'DashboardModule'

I've imported the module as suggested in my module, but I don't know why it hangs.

Please help!

**Comment by swiety85** [comment]
Yep, unfortunately I have to admit that project has problems with dev environment and therefore problems with dependencies, aot compilation, tslint etc. I will provide new env that should fix these issues and adopt it to use with aot as soon as possible.
Sorry for inconveniences. :)

**Comment by swiety85** [comment]
All issues with compilation should be fixed, including AOT. Please checkout v. 0.4.0.

**Comment by dedalusmax** [comment]
doesn't work for me.

**Comment by swiety85** [comment]
I've checked it with angular-cli. Do you have still the same issue: "Error: Unexpected value 'GridsterModule' imported by the module 'DashboardModule'"?
Can you tell me something more about your env, that I can try to reproduce the problem on my local machine?

**Comment by dedalusmax** [comment]
this is my package.json:

{
  "name": "angular2-webpack",
  "version": "1.0.0",
  "description": "A webpack starter for Angular",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 8080",
    "test": "karma start",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "2.4.0",
    "@angular/compiler": "2.4.0",
    "@angular/core": "2.4.0",
    "@angular/forms": "2.4.0",
    "@angular/http": "2.4.0",
    "@angular/platform-browser": "2.4.0",
    "@angular/platform-browser-dynamic": "2.4.0",
    "@angular/router": "3.4.0",
    "@webcomponents/custom-elements": "1.0.0-alpha.3",
    "clarity-angular": "0.8.4",
    "clarity-icons": "0.8.4",
    "clarity-ui": "0.8.4",
    "core-js": "2.4.1",
    "jquery": "3.1.1",
    "mutationobserver-shim": "0.3.2",
    "moment": "2.17.1",
    "ng2-translate": "5.0.0",
    "rxjs": "5.0.1",
    "zone.js": "0.7.4"
  },
  "devDependencies": {
    "@types/jasmine": "2.5.41",
    "@types/jquery": "^2.0.39",
    "@types/node": "^6.0.45",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "css-loader": "^0.23.1",
    "copy-webpack-plugin": "^4.0.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "~3.9.1",
    "gulp-util": "~3.0.8",
    "tslint": "^4.5.1",
    "gulp-tslint": "^7.1.0",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "node-sass": "~4.3.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "sass-loader": "~4.1.1",
    "style-loader": "^0.13.1",
    "typescript": "~2.0.10",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}

i also downloaded the component manually afterwards, so this is not inthere.

my vendor.js:
...
import 'angular2gridster';

webpack.dev.js:

var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');

module.exports = webpackMerge(commonConfig, {
  devtool: 'source-map',

  output: {
    path: helpers.root('Output'),
    publicPath: 'http://localhost:8080/',
    filename: '[name].js',
    chunkFilename: '[id].chunk.js'
  },

  plugins: [
    new ExtractTextPlugin('[name].css')
  ],

  devServer: {
    historyApiFallback: true,
    stats: 'minimal'
  }
});

webpack.common.js:

var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var helpers = require('./helpers');

module.exports = {
  entry: {
    'polyfills': './src/polyfills.ts',
    'vendor': './src/vendor.ts',
    'app': './src/main.ts'
  },

  resolve: {
      extensions: ['', '.ts', '.js', '.json', '.css', '.scss', '.html']
  },

  module: {
    loaders: [
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'angular2-template-loader']
      },
      {
        test: /\.html$/,
        loader: 'html'
      },
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file?name=assets/[name].[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
      },
      {
        test: /\.css$/,
        include: helpers.root('src', 'app'),
        loader: 'raw'
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loaders: ["style-loader", "css-loader", "sass-loader"]
      }
    ]
  },

  plugins: [
    new webpack.ProvidePlugin({
        jQuery: 'jquery',
        $: 'jquery',
        jquery: 'jquery'
    }),

    new webpack.optimize.CommonsChunkPlugin({
      name: ['app', 'vendor', 'polyfills']
    }),

    new HtmlWebpackPlugin({
      template: 'src/index.html'
    }),

    new CopyWebpackPlugin([
			{ from: 'i18n/', to: 'i18n' },
            { from: 'src/app/config/', to: ''}
    ])
  ]
};


as you can see, it's pretty standard.

**Comment by swiety85** [comment]
Shouldn't in this case "import 'angular2gridster';" be placed in "./src/vendor.ts" rather than in vendor.js?

**Comment by dedalusmax** [comment]
no, that's the configuration I use, and it's working fine.

**Comment by swiety85** [comment]
"import ..." statement in JS file seams to me a little bit odd. This statement normally should placed only in .ts files and these files are transpiled by webpack to .js. "import .." statement from .ts file is converted to something like: __webpack_require__(...) in js file. 
..but maybe in your case it's different.. 
I will try to create similar project out of your configurations and try to reproduce this issue. This is the only way I can understand where is the problem...

**Comment by michaelfaisst** [comment]
@swiety85 Any updates on this?

**Comment by swiety85** [comment]
I've created sample project based on [Angular guide with webpack](https://angular.io/docs/ts/latest/guide/webpack.html) to find the issue. 
I put `import 'angular2gridster'` in `vendor.ts` (not `vendor.js`) and than I import `GridsterModule` in `app.module` like it's described in [project readme](https://github.com/swiety85/angular2gridster#installation).
With these small steps I was able to easily run app with `angular2gridster` dashboard.
It seams that problem rather lays somewhere in your project configuration, not `angular2gridster` module.
Here you can download sample project that I've created [angular-webpack.zip](http://wajdlich.hostit.pl/angular-webpack.zip). I hope this will help you to solve the problem.
In case of any more questions, don't hesitate to ask.
