### ISSUE TITLE
Gridster inside gridster

### ISSUE THREAD

**Issue by rodrianderson** [swiety85/angular2gridster#123]
It's possible to insert a `<gridster>` inside a `<gridster-item>` element?

Something like:

`<gridster> <!-- outter -->`
  `<gridster-item> <!-- item from outter -->`
    `<gridster> <!-- inner -->`
      `<gridster-item> <!-- item from inner gridster -->`
     `</gridster-item>`
   `</gridster>`
  `</gridster-item>`
`</gridster>`

sry for the confusion :x

**Comment by rodrianderson** [comment]
When using Drag, the function is called twice  "addWidgetFromDrag(field, $event)", would have solution?

**Comment by swiety85** [comment]
Hi, I've tried it and it seams that most of things works. I only found an issue with resize handler and maybe with drag handler if it's the same for both - parent and nested gridster.
Except of that it seams to work correctly.
I will provide fix for problems above in nearest release.
I don't see problem with `addWidgetFromDrag`, can you provide same code or better - some ready to use example?

**Comment by rodrianderson** [comment]
I know your component does not have this functionality, but I'd like to implement it.

I created a component for Gridster '<gridster> </ gridster>'

as follows

![capturar1](https://user-images.githubusercontent.com/7784973/32074661-e1ff57a0-ba78-11e7-8b76-634326c9605b.PNG)
![capturar2](https://user-images.githubusercontent.com/7784973/32074662-e2258c18-ba78-11e7-8694-3f15aeee850b.PNG)

**Comment by rodrianderson** [comment]
I do not know if it is now easier to understand?

**Comment by rodrianderson** [comment]
It's possible to insert a  `<gridster> ` inside a  `<gridster-item>` element?


    `widgets: Array<any> = [
         {
            x: 1, y: 0, w: 2, h: 2,
            dragAndDrop: false,
            resizable: true,
            title: 'Gridster in gridster',
			widgets2: 
			[
				{
					x: 0, y: 0,
					w: 2, h: 2,
					dragAndDrop: true,
					resizable: true,
					title: 'gridster item or gridster'
				},
				{
					x: 1, y: 0, w: 2, h: 2,
					dragAndDrop: true,
					resizable: true,
					title: 'gridster item or gridster'
				},
				{
					x: 1, y: 1, w: 2, h: 2,
					dragAndDrop: true,
					resizable: true,
					title: 'gridster item or gridster'
				}
			]
        }
    ];`


![grister_sample](https://user-images.githubusercontent.com/7784973/34221096-ea27397a-e59d-11e7-98fc-4bf67c5f68ac.png)

![video](https://user-images.githubusercontent.com/7784973/34221044-c42a8182-e59d-11e7-9960-86b76f260940.gif)

**Comment by rodrianderson** [comment]
Good morning, could you help me with this doubt?

**Comment by swiety85** [comment]
I will try to provide solution for this problem this month.

**Comment by rodrianderson** [comment]
thank you!

**Comment by cmark11** [comment]
What is the status of this? I am interested in this too.

**Comment by swiety85** [comment]
I'm currently working on that. Since this is not trivial problem it takes time to implement.
@cmark11 Please provide clearer explanation of what you expect, best with some example.

**Comment by richardlnnr** [comment]
I have the same problem that @rodrianderson reported

**Comment by richardlnnr** [comment]
@swiety85 can I help you from something?
I had find a bug at gridList.ts in fixItemsPositions method.
The this.items has an element with itemPrototype as GridsterItemPrototypeDirective and $element null.

```
        this.items.forEach((itm: GridListItem) => {
            const cachedItem = gridList.items.filter(cachedItm => {
                return cachedItm.$element === itm.$element;
            })[0];
            // When itm.$element is null, the cachedItem will be undefined and the next line will crash
            itm.setValueX(cachedItem.x, options.breakpoint);
            itm.setValueY(cachedItem.y, options.breakpoint);
            itm.w = cachedItem.w;
            itm.h = cachedItem.h;
            itm.autoSize = cachedItem.autoSize;
        });
```

For fire this event, just resize a component in the demo.

**Comment by swiety85** [comment]
@richardlnnr Sorry, but I can't reproduce this bug. Can you provide more details how to reproduce it?

**Comment by richardlnnr** [comment]
Run your demo, drag a component inside "Basic form inputs 2" and resize the "Basic form inputs 2"

![image](https://user-images.githubusercontent.com/6029690/38320351-bf2e8a6a-380a-11e8-81a1-b02f7b7e4bca.png)

![image](https://user-images.githubusercontent.com/6029690/38320383-cc5698ae-380a-11e8-868a-bb15d9a7ae3e.png)

![image](https://user-images.githubusercontent.com/6029690/38320418-e5cd55e8-380a-11e8-97f6-e3b100173e13.png)

After this steps, see the console.

**Comment by swiety85** [comment]
Yes, sure. Current master branch does not support dragging with nested gridsters. 
I work on this feature on this branch: https://github.com/swiety85/angular2gridster/tree/123-Gridster-inside-gridster?files=1. I did not release it yet because I found some problematic bugs, I have to fix first. Thanx for patience

**Comment by richardlnnr** [comment]
I'm using a 123-Gridster-inside branch.
Sometimes, the gridster position is wrong :-)

![floating bug](https://user-images.githubusercontent.com/6029690/38321235-54ddbe30-380d-11e8-82ed-078b8b61be7a.gif)

**Comment by swiety85** [comment]
Exactly, this is one of the issue I have to fix. 😊

**Comment by richardlnnr** [comment]
Can I help you to fix this things? :-)

**Comment by swiety85** [comment]
The problem you found is already fixed. It's pushed. There is still some problem with dragging the item prototype after couple time moving out and over gridster area - especially when you drag to the very bottom of the window.

**Comment by swiety85** [comment]
It seems that it works now. Can you pull changes on [123-Gridster-inside-gridster](https://github.com/swiety85/angular2gridster/tree/123-Gridster-inside-gridster) branch and check if it's working fine for you now?

**Comment by richardlnnr** [comment]
It seems much better :-D
I found more two bugs.
The first occur when floating is enabled. (This is a bug?)
![float-insert](https://user-images.githubusercontent.com/6029690/38334981-48f35794-3833-11e8-918a-ce2231ea9628.gif)

And this
![add-new-item](https://user-images.githubusercontent.com/6029690/38335004-55eca798-3833-11e8-819d-ce36ce42e790.gif)

**Comment by swiety85** [comment]
I fixed these issues. Please give it the next try. I also fixed some issues with resizing - have a look at it as well.
There is one known to me issue that is not fixed: when you will have an item with long content (with scroll) and you will drag under this item, the main (parent) girdster will not react because "item nested gridster" will catch it. It happens because of overflowed content.
It seems to be not so easy to fix. I will have a look at that still in this week.
If it's urgent for you fill free to find a solution for this problem on your own as well.
Thx!

**Comment by richardlnnr** [comment]
Good morning.
You're amazing.
That's working very well.

**Comment by swiety85** [comment]
Thx for the compliments. :)
I provided some additional fixes and adjustments. The problem mentioned above is also fixed.
You asked me if you can help me, so... I would appreciate if you will test it once again (in general) and approve it that I can soon release this feature.

**Comment by richardlnnr** [comment]
That's all right. I have only a CSS change in the demo.
The gridster area is not showing.
![image](https://user-images.githubusercontent.com/6029690/38420768-41add31c-397b-11e8-90ef-30dc1e8f83d6.png)

When I comment this CSS code in app.component.css
```
:host {
    position: absolute;
    /*
    display: flex;
    display: -webkit-inline-box;
    flex-direction: column;
    */
    height: 100%;
    width: 100%;
    overflow: hidden;
}
```
The Gridster appears.
![image](https://user-images.githubusercontent.com/6029690/38420901-b7f763b2-397b-11e8-88dd-124c93229728.png)

**Comment by richardlnnr** [comment]
I have two questions :-)

It's possible to prevent an child gridster to interact with an specific gridsterItemPrototype?
Example: The gridsterItemPrototype "Drag me (clone) 1x1" can be dragged in any gridster.
But the gridsterItemPrototype "Drag me (clone) 1x2" can be dragged only on the main gridster.
Has a way to do this?

It's possible to drag an element into main gridster to child gridster? And the opposite also.

![drag-inside](https://user-images.githubusercontent.com/6029690/38421607-133147dc-397e-11e8-9b55-16ea2b170949.gif)

**Comment by swiety85** [comment]
I have no clue why your gridster area is not visible. I didn't change anything in CSS. I can't reproduce it in any browser. Did you change anything in styles or ViewEncapsulation?
About two questions - both things are not supported by now. I can provide these features but not altogether in one merge. Just create separate issues.
P.S. Could you tell me what is your use case of having "nested gridster" functionality?

**Comment by richardlnnr** [comment]
When I launch the demo in Google Chrome and Edge, and the gridster area is on the right (No CSS change)

![gridster-css](https://user-images.githubusercontent.com/6029690/38424964-0251bb26-3989-11e8-90dd-b02f503ea380.gif)

About two questions, I'll create issues to make this features :-)
In reply your question, I have a simple element on the first prototype, it's only a label and can be dragged in any gridster.
And in the second prototype I have a more complex element with a Gridster inside.
I need to prevent a insertion of a element that is a gridster inside a child gridster.

Could I open the two issues?
Thanks for all your help :-)

**Comment by swiety85** [comment]
Please also create two issues for these two question you have. Thanx!
Can you tell me which version of Chrome you use? Did you have this problem before my last changes?

**Comment by richardlnnr** [comment]
65.0.3325.181 (Oficial Version) 64 bits.
I have the last changes in my workspace.

**Comment by richardlnnr** [comment]
Thanks @swiety85 
You're amaizing :-)

**Comment by delashum** [comment]
How do you actually use the gridster inside of another? I did what seemed intuitive but in my child gridsters none of the items can be moved around. Can't see an example anywhere either.
