### ISSUE TITLE
Grids are not displaying according to their positions

### ISSUE THREAD

**Issue by anushamramyam** [swiety85/angular2gridster#124]
Grids are not displaying according to their positions.

The widgets configuration is,
  widgets: Array<any> = [
        {
            x: 0, y: 0,
            w: 1, h: 1,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 1'
        },
        {
            x: 2, y: 0, w: 1, h: 1,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 2'
        },
        {
            x: 4, y: 0, w: 1, h: 1,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 4'
        },
    ];

The html is,

    <gridster [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions"
              (optionsChange)="optionsChange($event)" #gridster1 style="min-height: 500px;">

        <gridster-item *ngFor="let widget of widgets; let indx = index" #itemComp
                       [options]="itemOptions"
                       [dragAndDrop]="widget.dragAndDrop" [resizable]="widget.resizable"
                       [(x)]="widget.x" [(y)]="widget.y"
                       [(xSm)]="widget.xSm" [(ySm)]="widget.ySm"
                       [(xMd)]="widget.xMd" [(yMd)]="widget.yMd"
                       [(xLg)]="widget.xLg" [(yLg)]="widget.yLg"
                       [(xXl)]="widget.xXl" [(yXl)]="widget.yXl"
                       [(w)]="widget.w" [(h)]="widget.h"
                       (change)="itemChange($event, gridster1)">

            <div class="panel-heading">
                <h5 class="panel-title">{{ widget.title }}</h5>
            </div>

            <div class="panel-body">
                <app-test></app-test>
            </div>

        </gridster-item>

    </gridster>

I have attached screenshot of this output, PFA.
![gridview](https://user-images.githubusercontent.com/31650367/32001830-91eaedbc-b9b8-11e7-9a56-c4f34b9d802e.png).

According to widgets configuration widgets are not rendered.

**Comment by swiety85** [comment]
Hi, send me please your `gridsterOptions` configuration.

**Comment by anushamramyam** [comment]
gridsterOptions: IGridsterOptions = {
        // core configuration is default one - for smallest view. It has hidden minWidth: 0.
        lanes: 4, // amount of lanes (cells) in the grid
        direction: 'vertical', // floating top - vertical, left - horizontal
        dragAndDrop: true, // enable/disable drag and drop for all items in grid
        resizable: true, // enable/disable resizing by drag and drop for all items in grid
        widthHeightRatio: 1, // proportion between item width and height
        shrink: true,
        responsiveView: true, // turn on adopting items sizes on window resize and enable responsiveOptions
        responsiveDebounce: 500, // window resize debounce time
        responsiveOptions: [
            {
                breakpoint: 'sm',
                // minWidth: 480,
                lanes: 3
            },
            {
                breakpoint: 'md',
                minWidth: 768,
                lanes: 4
            },
            {
                breakpoint: 'lg',
                minWidth: 1250,
                lanes: 6
            },
            {
                breakpoint: 'xl',
                minWidth: 1800,
                lanes: 8
            }
        ]
    };

**Comment by swiety85** [comment]
If you have `responsiveView: true` and responsive options defined, `x` and `y` works for smallest responsive breakpoint 0-480px.
If you want to have responsive breakpoint and set it for current view you should use (I guess) `xLg` and `yLg` bindings.
If you want one positions works for all breakpoint, just remove `responsiveOptions` and set `responsiveView: false`.

**Comment by anushamramyam** [comment]
Hi, 

Thank you for your reply.

I have changed gridsterOptions as below, but the grids are not displaying according to widget configuration.
    gridsterOptions: IGridsterOptions = {
        // core configuration is default one - for smallest view. It has hidden minWidth: 0.
        lanes: 4, // amount of lanes (cells) in the grid
        direction: 'vertical', // floating top - vertical, left - horizontal
        dragAndDrop: true, // enable/disable drag and drop for all items in grid
        resizable: true, // enable/disable resizing by drag and drop for all items in grid
        widthHeightRatio: 1,
        responsiveView: false,
        responsiveDebounce: 500, // window resize debounce time
    };

**Comment by anushamramyam** [comment]
Hi,

Sorry, I didn't observe properly. It is working. Thank you very much.
