### ISSUE TITLE
Is there any way to give width and height as in percentages

### ISSUE THREAD

**Issue by anushamramyam** [swiety85/angular2gridster#125]
Hi,

Is there any way to give width and height as in percentages, since you are calculating the width and height and mentioning as  in pixels using translate().

**Comment by swiety85** [comment]
I'm not sure if I got you right.. If you want to set sizes for items from percentage values, you can easily convert it e.g. by this simple function:
```js
covertPercentageToLanes(percentageValue, totalLanesAmount) {
    return parseInt((percentageValue/100) * totalLanesAmount, 10);
}
...
item.w = this.covertPercentageToLanes(50, 8)
```

**Comment by anushamramyam** [comment]
Hi,
Thank you for your reply.

Can you clarify where should I add this snippet.Currently the element level css are in pixel.

Let me clarify the requirements.
 I want to make elements as responsive. The plugin is providing responsiveness on window resize, but according to the requirements, the elements(gridster-items) are nested in another widget, on resize of widget the elements should be responsive.
I have attached screenshot, PFA.
![beforeresponsive](https://user-images.githubusercontent.com/31650367/32088893-5e0bc2f8-bb04-11e7-86ca-0131ffa4dc17.png)



On resizing the widget, the elements are not responsive since element level css are in pixels.

I have attached screenshot on resize of widget, PFA.
![afterrisize](https://user-images.githubusercontent.com/31650367/32089097-99ab683a-bb05-11e7-9ed8-ae4b01ec3324.png)

 
Please let me know if  any information is required to understand.

**Comment by swiety85** [comment]
Hi, sorry the you had to wait so long.
Using percentage values would be cool, but using this approach would provide some problems and open question in the way Gridster is working.
Regardless of that, I can provide you quite ease solution of your problem. The only thing, that you need is the handler for container element resize. There you can call `gridster.reflow()` method that is responsible for calculating and rerendering items accordingly:
```js
@ViewChild(GridsterComponent) gridsterComponent: GridsterComponent;
// it's worth to consider using debounce on native resize event to have better preformance
onContainerResize() {
  this.gridsterComponent.gridster.reflow();
}
```
Give a hint, if it helps you.

**Comment by anushamramyam** [comment]
Hi,

Thank you for you reply. I will try this now.

**Comment by anushamramyam** [comment]
Hi,

The above solution is working.

In our case it is different . I have used the below library for to detect element changes.
https://github.com/sdecima/javascript-detect-element-resize

Then given unique ID for div on in ngAfterViewInit() called reflow().

 ngAfterViewInit() {
        $('#formBuilderComp' ).resize(() => {
            this.gridster.gridster.reflow();
        });
    }

Thank you for providing the solution.
