### ISSUE TITLE
Bad new item position calculation on dragging.

### ISSUE THREAD

**Issue by islimane** [swiety85/angular2gridster#126]
Hi,

My problem is that when I drag an item on a srolled window, automatically it's moved to the top of the body, outside the visible window.
Unlike the demo, I have inserted the gridster inside another element that has "overflow-y: scroll" and the body has "overflow: hidden", I think this is the problem. Is there a solution?

Thanks.

**Comment by swiety85** [comment]
In demo Gridster is placed in element with `overflow: auto;`. Which version of Angular2gridster do you use? There was a bug related to this use case, but it was fixed in v.0.6.8.

**Comment by islimane** [comment]
@swiety85 Right, this was fixed with v.0.6.8.

Thank you!
