### ISSUE TITLE
Getting error when drag widget to grid in IE 11 browser

### ISSUE THREAD

**Issue by saranga-rathnayake** [swiety85/angular2gridster#128]
In IE 11 browser, it gives following error when drag items to grid and prevent from dragging.

`SCRIPT5007: Unable to get property 'blur' of undefined or null reference`

![issue-ie](https://user-images.githubusercontent.com/22959475/32487565-08757b3e-c3d0-11e7-8c9b-a2409218826a.jpg)
Steps to reproduce,

1. Go to https://swiety85.github.io/angular2gridster/ in IE 11 browser
2. Remove all existing widgets
3. Try to add first widget, if you didn't get the error, try removing it and adding it again.

**Comment by saranga-rathnayake** [comment]
I tried commenting out line 61 in gridster\utils\draggable.ts and it seems working fine.
`(<any>document.activeElement).blur();`

**Comment by swiety85** [comment]
The problem should be fixed in v1.0.0-alfa.

**Comment by saranga-rathnayake** [comment]
excellent.
