### ISSUE TITLE
has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by awaisaltaf** [swiety85/angular2gridster#129]
Hi guys, 
i am having this error while importing into module.
![angular2gridster](https://user-images.githubusercontent.com/10347603/32650440-92880b38-c61f-11e7-891b-f284af24bb85.png)

**Comment by swiety85** [comment]
Hi, which Angular version do you use in your project?

**Comment by awaisaltaf** [comment]
2.4.10

**Comment by swiety85** [comment]
Seams that it's compatibility problem. I would suggest to upgrade you project to Angular 4 or higher.
Never the less, I will have a look if it's possible to fix this problem to make it work with Angular 2 as well.

**Comment by swiety85** [comment]
The angular2gridster supports Angular version since version 4.
