### ISSUE TITLE
Mouse over scrollbar results in resize

### ISSUE THREAD

**Issue by pienaarp** [swiety85/angular2gridster#135]
When I move my mouse anywhere over the scroll bar of a widget / gridster item, the mouse cursor changes to resize.  Therefore I can't scroll the contents of a widget up or down.  The mouse cursor should only change to resize over the resize handle in the bottom left corner.  Running in Chromium 62 on Ubuntu 16.04.

**Comment by swiety85** [comment]
Hi, good that you point it. Since different systems has different requirements, we will provide configuration for resize handles e.g.
```js
resizeHandles: {
      s: true,
      e: true,
      n: true,
      w: true,
      se: true,
      ne: true,
      sw: true,
      nw: true
    }
```
When you would like to allow resize on bottom-right corner only, you would have to set following config:
```js
resizeHandles: {
    sw: true // south-west
}
```
Would it be ok for you?

**Comment by pienaarp** [comment]
Hi, yes that sounds perfect - thanks for the prompt response. Appreciate
your work
