### ISSUE TITLE
Adopt module to work with angular 4

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#14]
From comments in #11 it seams that npm module in v 0.4.0 does not work with angular 4.
Research and fix an issue.

**Comment by DinkuMM** [comment]
Yes please check. Might be i am doing something wrong. have you check at your sid.

**Comment by swiety85** [comment]
The issue with angular 4 should be fixed in v. 0.4.1.
Please check and give write back if it works.
