### ISSUE TITLE
Scrolls when grid content dragged horizontally

### ISSUE THREAD

**Issue by dhamecha** [swiety85/angular2gridster#143]
I am using `1.0-alfa`. As I am using scroll on drag feature horizontally which scrolls horizontally and goes outside the gridster container. 

Is there any way to restrict horizontal scroll on dragged or resize?

**Comment by swiety85** [comment]
What you mean with restrict? I don't understand the problem. Please write some more info and/or create an example that I can better help you.

**Comment by dhamecha** [comment]
Visit demo app and drag a grid towards right corner. Check this ![gif](http://g.recordit.co/x4E17pEDEe.gif)

**Comment by swiety85** [comment]
I will restrict scroll to gridster `direction`. This should solve your problem. It's quite ease to implement, therefore I will provide this feature in nearest release.
