### ISSUE TITLE
Help!!

### ISSUE THREAD

**Issue by tssobe** [swiety85/angular2gridster#155]
Hi
I have a very very strange issue.
When I have 11 items or less on the grid, everything is working perfect.
Once I add more than 11 items the grid get messy.
I have digged up to the source code into gridList.js and found a strange issue.
In method GridList.prototype.sortItemsByPosition = function () {..}
and in this.items.sort(function (item1, item2) , once the grid contains more than 11 items, the item 2 is not the item 2 from the items but item number 10.
If I have less than 12 items, item 1 is item 1 from the list, and item 2 is item 2 from the list.
I assume the grid get messy because of this.
When I mean the grid get messy, is that item 10 go to the top of the grid for no reason and shift other items. When less than 12 item this doesn't happen.
I don't understand the source issue and how to solve it.
I am using "angular2gridster": "0.5.3"
Thanks,
Tsahar

**Comment by rudzikdawid** [comment]
why You dont use latest release?

**Comment by tssobe** [comment]
Works now, I am now using the latest version.
Thanks!!
