### ISSUE TITLE
Using ngrx as Widgets store

### ISSUE THREAD

**Issue by gentle9** [swiety85/angular2gridster#156]
Hi,

I a want to use ngrx for storing the state of gridster. When a widget is moved or resized I want to update the state in ngrx and using ngrx to store the state in my backend.

I have already implemented the async loading part from ngrx and it is working very good.
But now I have two problems that I dont know how to solve. If I do update the widget in the ngrx store when it is moved or resized gridster rebuilds the complete widgets I think because there is a new state. The problem here is that I get an infinite loop and when other widgets reflows because of the change the gridster is rebuilding multiple times. A workaround could be to not update the ngrx state on change and only update the backend but that seems not right to because the state would not represent the real state.
Is there any way to use it correctly with ngrx?

**Comment by swiety85** [comment]
Hi,
I've connected rxjs/store to my demo project and I've tried to reproduce your problem, but I can't.
Can you have a look on branch [156-Using-ngrx-as-Widgets-store](https://github.com/swiety85/angular2gridster/tree/156-Using-ngrx-as-Widgets-store)? This version of demo uses rxjs/store to manage states of widgets and sync it with localstorage.
If this does not help, I would suggest to share with me the code or create some sample (e.g. jsFiddle), that I can better understand the case.

**Comment by gentle9** [comment]
Sorry I was busy and haven´t time to test it. I will provide some code for my problem. Right now I have implemented it with the workaround. But I still have another problem. If I use the (change) event like in the branch to update the widget in the store and have defined responsive options the event is fired for every responsive breakpoint when the widget is resized. So it issues multiple updates when a widget is resized.
