### ISSUE TITLE
Item lands on the top of another item and item is being moved to the left even with dicrection:none and floating:false

### ISSUE THREAD

**Issue by tw2as** [swiety85/angular2gridster#158]
I've came across issues awkward behaviour of items

Scenario 1 - item lands on the top of another item
1. Open demo app: https://swiety85.github.io/angular2gridster/
2. Remove all Gridster Items
3. Change Direction to None and switch off Floating (gravity)
4. Add first item by clicking on "Add widget without data" (Note that it's going to have: Position: 0 x 0 and Size: x )
5. Add second item by clicking again on "Add widget without data" (Note that it's going to have: Position: 1 x 0 and Size: x )
6. Clicking on "Width +" on second item is not changing the width of the item but instead it's bringing the item to the left (Note that afterwards it has: Position: 0 x 0 Size: NaN x ) and puts second item on the top of the first item. 

Scenario 2 - item is floated to the left (despite dicrection:none and floating:false)
1-5 - same steps as in Scenario 1
6. Remove first item
7. Clicking on "Width +" on second item is not changing the width of the item but instead it's bringing the item to the left (Note that afterwards it has: Position: 0 x 0 Size: NaN x ) 

Scenario 3 - new item lands on the top of existing item
1-7 - same steps as in Scenario 2
8. Add third item by clicking on "Add widget without data" - it lands on the top of second item (it's also possible to add a new item on the top of second item by drag)
9. Drag third item on a side to disclose second item and note that it has Position: NaN x 0 Size: NaN x

**Comment by swiety85** [comment]
Thanx for info. I will fix it as possible.

**Comment by swiety85** [comment]
Should work in v1.1.0
