### ISSUE TITLE
BUG: Grid does not honor global dragAndDrop options upon load

### ISSUE THREAD

**Issue by IAMtheIAM** [swiety85/angular2gridster#163]
Hi, if the grid is set to:

```
   gridsterOptions: IGridsterOptions = {
      dragAndDrop       : false,<--- false here
      resizable         : false, <--- false here
      resizeHandles     : {
         s : true,
         e : true,
         n : true,
         w : true,
         se: true,
         ne: true,
         sw: true,
         nw: true
      },
```

and the individual widgets are set to 

```
{
            x: 0, y: 0,
            w: 1, h: 2,
            dragAndDrop: true, <--- true here
            resizable: true, <--- true here
            title: 'Widget 1'
        },
        {
            x: 1, y: 0,
            w: 3, h: 1,
            dragAndDrop: true, <--- true here 
            resizable: true,<--- true here
            title: 'Widget 2'
        },
```

Then, upon load, the individual widget settings take priority over the global settings. This is backwards, the global setting of `false` should override the individual setting. That way the dashboard can be default be not draggable, then only upon clicking "edit" will it enable dragging as a global option.

This works upon clicking edit, then disabling edit, then clicking edit again. But for the initial load, the global options are ignored.

# Second bug

If the individual widgets are set to          `dragAndDrop: false`, and the global `gridsterOptions.dragAndDrop = true` , upon initial load the grid allows dragging, but the widgets no longer rearrange themselves. Instead, they overlap each other instead of reflowing.

**Comment by IAMtheIAM** [comment]
Thanks for the quick fix. Let me know and I will test for you once it is ready.

**Comment by swiety85** [comment]
Should work in v1.2.0.

**Comment by IAMtheIAM** [comment]
Works, thanks!
