### ISSUE TITLE
Is there a way widgets fit to screen

### ISSUE THREAD

**Issue by rajeshmuraleedharan** [swiety85/angular2gridster#17]
I would like to make widgets fit to screen and resizes automatically based on the available width and height?

**Comment by swiety85** [comment]
For now not. I planned this issue to be done in next milestone (0.6).

**Comment by swiety85** [comment]
"reload" method only recalculates widgets on board and update sizes, but probable using debounce or throttle is worth to consider in this case.

**Comment by swiety85** [comment]
Responsive behaviour will be implemented together with #19 issue.
