### ISSUE TITLE
Question! Writing own components to be rendered inside a Grid Item

### ISSUE THREAD

**Issue by kashipai** [swiety85/angular2gridster#172]
Hi,

Maybe a noob question

Is there any pointer as to how to go about writing a component, and rendering the same inside a Grid Item? 

So lets say there are around 4 or 5 Grid Items, and each would have a html from a particular component.

Thanks.

**Comment by swiety85** [comment]
I'm not sure, if I understood you right. Do you want to render different component inside different girdster-item?

**Comment by kashipai** [comment]
Yes exactly... I am planning to write a Angular components, so that those can be rendered inside a gridster-item, not actually getting how to go about it. Thanks for help.!

**Comment by swiety85** [comment]
You can use [ng-dynamic-component](https://github.com/gund/ng-dynamic-component) external module or you can try to use directly Angular native `ComponentFactoryResolver`, [here](http://blog.rangle.io/dynamically-creating-components-with-angular-2/) you have some article about it.
Hope this will help you. In case of any other question, ask.

**Comment by kashipai** [comment]
@swiety85 Thank you very much... Will look into it.
