### ISSUE TITLE
Grid lines still appear when drag widget on gridster area and drop outside gridster

### ISSUE THREAD

**Issue by PodeMarut** [swiety85/angular2gridster#173]
First of all, I apologize for my english is not so good.
I try out your [Demo](https://swiety85.github.io/angular2gridster/)
So i drag widget (Drag me (Clone) 1x1) into gridster area then grid lines appear.
But i don't want drop this widget in gridster i drop this widget outside gridster but grid lines still appear.
I think grid lines should disappear. 
Thank you for your advice! 

![1](https://user-images.githubusercontent.com/24226386/34661128-14c2ed6a-f47a-11e7-84b4-81f1eb671ba2.png)
![2](https://user-images.githubusercontent.com/24226386/34661130-199e29bc-f47a-11e7-8012-9988f8719068.png)

**Comment by rudzikdawid** [comment]
Thank You for reporting

**Comment by PodeMarut** [comment]
Thank you! so much for fixed.
