### ISSUE TITLE
Unable to use it in my application

### ISSUE THREAD

**Issue by jangti** [swiety85/angular2gridster#176]
Please give proper installation steps. You have not given the installation steps properly.. where and how we need to include/add systemjs.config.js file. Do we need to create it? and I dont see system.js in my app. Please write proper installation steps. 
Error msg here : 
Uncaught Error: Template parse errors:
Can't bind to 'options' since it isn't a known property of 'gridster'. ("
  </div>
</div>
<gridster [ERROR ->][options]="gridsterOptions" [draggableOptions]="{ handlerClass: 'panel-heading' }">
  
    <gridster-"): ng:///DashboardModule/DashboardComponent.html@33:10
Can't bind to 'draggableOptions' since it isn't a known property of 'gridster'. ("
  </div>
</div>

**Comment by swiety85** [comment]
Does your app is based on [System.js](https://github.com/systemjs/systemjs), or does it use webpack/angular CLI?

**Comment by jangti** [comment]
it use webpack.. pls help

**Comment by rudzikdawid** [comment]
Please write proper description of your project.
link to repository ? content of `package.json` ?
