### ISSUE TITLE
Determining position of item on insert

### ISSUE THREAD

**Issue by Blackbaud-XandraHarrison** [swiety85/angular2gridster#177]
In our application, we give users the option to either drag in a widget to a specific position or click the widget and allow the grid to place the widget in the next available spot. This works perfectly for the drag functionality because the x and y positions are given by the drop event so we can save them and reload them when the whole board is opened again. 

When the widgets are added by click, they populate to the next available spot as expected. However, the x and y values saved are not the same as the spot they populate in the ui. (I believe this may be due to gridster automatically assuming the smallest breakpoint.) Is there a way to get the actual position of the added widget without the item given by the drop event?

**Comment by swiety85** [comment]
Hi, it would be good to see some code to fully understand your case and problem. For now I can say that two way binding should update position automatically after item is added. You should only remember that "current" position (for current breakpoint) can have different prop name e.g. `xLg` and `yLg`.
Another way to react on changing/applying items data by gridster component is to use `change`  output attribute of `GridsterItem` component e.g. `(change)="onWidgetChange($event, gridster, widget)"`.
In this case you can read current position (in current breakpoint) of an item that has changed by following code:
```js
onWidgetChange($event, gridster, widget) {
    if ($event.breakpoint === gridster.options.breakpoint) {
        console.log('Widget position for current breakpoint', widget, $event.item.x, $event.item.y);
    }
}
```
Hope this help you anyhow.

**Comment by Blackbaud-XandraHarrison** [comment]
I suppose the issue is that the added item is from a prototype directive so there isn't an x and y value to bind to. On the drag event in the prototype directive, we can grab the x and y values from the item passed in, but without the event I'm not sure how to access the created item's position.

**Comment by swiety85** [comment]
Sorry for late response. I miss it somehow.
Please have a look how this problem is solved in the [demo](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.ts#L182).
