### ISSUE TITLE
resized coordinates of widget is saved in db but re- positioning is not updating 

### ISSUE THREAD

**Issue by ashavyshakh** [swiety85/angular2gridster#181]
My html template is as follows
`  <gridster-item *ngFor="let widget of widgets" (change)="gridChange(widget)"
                     [(x)]="widget.dashboardView.position.x" [(y)]="widget.dashboardView.position.y"
                     [(w)]="widget.dashboardView.position.w" [(h)]="widget.dashboardView.position.h"
                     style="background-color:#ffff;border:1px solid red" >
                     <div [innerHTML]="widget.dashboardView.html | noSanitize">
                     </div>
      </gridster-item>`

And in my ts file  I ve given
`this.gridsterOptions = {
      lanes: 2, // how many lines (grid cells) dashboard has
      direction: 'vertical', // items floating direction: vertical/horizontal/none
      floating: true, // default=true - prevents items to float according to the direction (gravity)
      dragAndDrop: true, // possible to change items position by drag n drop
      resizable: true, // possible to resize items by drag n drop by item edge/corner
      useCSSTransforms: false, // Uses CSS3 translate() instead of position top/left - significant performance boost.
      swapping: true,
      // ResponsiveOptions can overwrite default configuration with any option available for specific breakpoint.
      responsiveOptions: [
        {
          breakpoint: 'sm',
          lanes: 3
        },
        {
          breakpoint: 'md',
          minWidth: 768,
          lanes: 4,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'lg',
          lanes: 6,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'xl',
          minWidth: 1800,
          lanes: 8,
          dragAndDrop: true,
          resizable: true
        }
      ]
    };`

My dragging event is not updating(X,Y coordinates binding is not working) . after reloading the page, widgets are on the initial position.

**Comment by swiety85** [comment]
Hi, if you use responsive options, then coords are assigned by for specific breakpoint:

- till `sm` (480px), it uses `x` and `y` attributes
- `sm` (480px - 768px), it uses `xSm` and `ySm` attributes
- `md` (768px - 1250px), it uses `xMd` and `yMd` attributes
- `lg` (1250px - 1800px), it uses `xLg` and `yLg` attributes
- from `xl` (1800px), it uses `xXl` and `yXl` attributes

**Comment by ashavyshakh** [comment]
Ok thank you. That means i need to change mh html template s as well right?

**Comment by ashavyshakh** [comment]
Thank you so much for your valuable help. My issue is fixed. Its working fine
