### ISSUE TITLE
Not able to Use Last lane.

### ISSUE THREAD

**Issue by hardikBharadava** [swiety85/angular2gridster#182]
Hi there,
Have using you library, and having 40 lanes. On Your demo page it is also replicate,
Issue is, when I'm having 40 lanes or maybe more than 40, (haven't tested yet) than last lane is not usable.
You can see in attached screen recording of your demo page.
Attaching a [Screen Record](https://www.screencast.com/t/s3Lar9LjygHz) of your Demo page.
If there is any specific Logic to select lanes than let me know, or it is free to select any number of lanes.
Regards.

**Comment by swiety85** [comment]
Sorry, but i can not reproduce this problem on demo page. Could you attach screen record not in flash?

**Comment by swiety85** [comment]
Because of no response I am forced to close an issue.
