### ISSUE TITLE
While there's a single lane, widgets can only be drag/dropped all the way up/down

### ISSUE THREAD

**Issue by SelStefan** [swiety85/angular2gridster#183]
*Steps to reproduce*
* Set the gridster instance to have only 1 lane
* Drag one of the widgets and try to drop it somewhere

*Result:*
* Widgets can only be dropped all the way up or all the way down in the container

*Expected result:*
* It should be possible to drop widgets between other widgets
![demo](https://user-images.githubusercontent.com/12737071/35510307-e27c1938-04f7-11e8-934f-a504dc2b4f49.gif)

But then when you touch the resize handlers, the widgets drop properly again:
![demo 1](https://user-images.githubusercontent.com/12737071/35510390-2ada0190-04f8-11e8-87c2-1d5db955c887.gif)

**Comment by swiety85** [comment]
I can confirm this bug. Than you for reporting.
