### ISSUE TITLE
Can I set the row similar to how lines can be set?

### ISSUE THREAD

**Issue by sutandan** [swiety85/angular2gridster#184]
For example want to set 5 columns and 4 rows. Presently columns can be set using lanes I cannot see any row option though.

**Comment by swiety85** [comment]
Hi,
rows are generated dynamically. Their amount depends on the position and size of items on the board.
If you ask about how to make fixed amount of rows in gridster, then the answer is unfortunately, that it's not possible for now. 
It is planned in [Roadmap](https://github.com/swiety85/angular2gridster/wiki/Roadmap) - Fit gridster to window (horizontally and vertically), but this will not rather implemented in nearest releases.
