### ISSUE TITLE
unable to set Item position (x,y) at startup (or at any other moment)

### ISSUE THREAD

**Issue by andrisarkameru** [swiety85/angular2gridster#185]
Hi! I seem to be liking your library and hope I can use it in my project. 
It seems that I am unable to set grid item positioning (x,y) when creating the grid or binding the positions through variables. 

I tried going by example and every time the items spawn at positions closest to upper side.

Even when I put a test example of: 
```
 <gridster-item [x]=2 [y]=2> Test Element </gridster-item>
```
The item spawns at position 0,0. 

Btw - sizing (h, w) works and I am even able to save size between reloads. But the positioning sadly does not. 

The floating is off, so that sould not be happening. 
My options are as follows:
```
options = {
            lanes: 2, // how many lines (grid cells) dashboard has
            direction: 'vertical', // items floating direction: vertical/horizontal/none
            floating: false, // default=true - prevents items to float according to the direction (gravity)
            dragAndDrop: true, // possible to change items position by drag n drop
            resizable: true, // possible to resize items by drag n drop by item edge/corner
            useCSSTransforms: true, // Uses CSS3 translate() instead of position top/left - significant performance boost.
            // ResponsiveOptions can overwrite default configuration with any option available for specific breakpoint.
            lines: { visible: true, color: '#d800d8', width: 1 },
            gridsterPositionChange: function (obj) { console.warn("wChange", obj) },
            responsiveOptions: [
                {
                    breakpoint: 'sm',
                    lanes: 3
                },
                {
                    breakpoint: 'md',
                    minWidth: 768,
                    lanes: 4,
                    dragAndDrop: true,
                    resizable: true
                },
                {
                    breakpoint: 'lg',
                    lanes: 6,
                    dragAndDrop: true,
                    resizable: true
                },
                {
                    breakpoint: 'xl',
                    minWidth: 1800,
                    lanes: 8,
                    dragAndDrop: true,
                    resizable: true
                }
            ]
        }
```
And the gridster html declaration is 
```
<gridster #gridsterComp [options]="gridsterOptions" [draggableOptions]="{ handlerClass: 'panel-heading' }" (gridsterPositionChange)="positionsChanged($event)"
            (resize)="itemResize($event)">
```

**Comment by swiety85** [comment]
Hi,
your problem most probably is related with `responsiveOptions` that you set in gridster configuration. If you use responsive options, then coords are assigned by for specific breakpoint:

- till `sm` (480px), it uses `x` and `y` attributes
- `sm` (480px - 768px), it uses `xSm` and `ySm` attributes
- `md` (768px - 1250px), it uses `xMd` and `yMd` attributes
- `lg` (1250px - 1800px), it uses `xLg` and `yLg` attributes
- from `xl` (1800px), it uses `xXl` and `yXl` attributes

If you don't want to have different positions for different screen size, just remove `responsiveOptions`, otherwise you have to store different positions for different breakpoint like it's described above.
I will add also this information in readme.md soon.

**Comment by jangti** [comment]
Trying to set draganddrop option to true on some button event, it is accepting the value but drag is not happening.
ex : this.gridsterOptions.dragAndDrop = true;
Initially I set it to false, On some button click event I want to enable to drag option but its not happening please help.

**Comment by meyer20** [comment]
Hi there, 
I'm having the same problem, when i try to initialize my gridster list, the output (change) is fired and all my positions (x, y, xSm and ySm) is overwritten, and like @andrisarkameru all the positions (except width and height) receives the positions 0.

**Comment by speculees** [comment]
I noticed that if there are no responsive options and binding is to x and y the change event is not initiated on creation. But, if I activate responsive behavior, remove the x and y bindings and add the *Sm *Md *Lg *Xl bindings the change event is triggered on creation... This is when the overwriting occurs. That is why I currently have responsive options set to false... I thought the 1.2.1 update would fix this, so for now my hopes are for 1.2.2. :smiley:

**Comment by swiety85** [comment]
@jangti You should additionally call:
```js
gridster.setOption('dragAndDrop', true)
```
where `gridster` is the instance of gridster component. Have a look how it's done in [demo](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.html#L19).

**Comment by swiety85** [comment]
I will try to reproduce your problem with change event as well.

**Comment by jangti** [comment]
Hi swiety, 
I have got the solution, 
we should use @ViewChild (GridsterComponent) gridsterComp:GridsterComponent;
this.gridsterComp.reload();(In whichever the function we need to see the changes).

**Comment by swiety85** [comment]
Anybody that has the problem with `(change)` event please create a plunker example where I can reproduce a problem or detailed steps to reproduce it on demo app.
Thank you for your understanding

**Comment by rudzikdawid** [comment]
example http://dawid.ru/workspace/something
source: https://github.com/rudzikdawid/material2-start/tree/patients/src/app/workspace/something

to test: move widgets, resize widgets, **refresh browser page** `F5` or `Ctrl+Shift+R` 
after refresh your should see your changes.

in this example I use `localStorage` to keep widgets state.

## set Item position (x,y) at startup.
```
ngOnInit() {
  this.widgets$ = this.loadWidgets();
}
```

## save data.
the best way to save widgets state is using: `(end)` Outputs.
```
(end)="saveWidgets()"
```
`(end)` callback fires after we stop manipulating (moving/resizing) widgets

**Comment by andrisarkameru** [comment]
Sorry for not responding sooner, but my original issue was resolved, when I removed the responsive options. [x] and [y] binding started to work as it seems. Did not manage to test with breakpoints and responsive options.
