### ISSUE TITLE
Define _items in gridster.service.ts

### ISSUE THREAD

**Issue by gentle9** [swiety85/angular2gridster#187]
Hi,

is it possible to define the _items variable on line 19 in gridster.service.ts?
I have a two pages which are using the gridster plugin and using the same ngrx store for widgets. When switching from one page to the other some how it trys to remove the widget (first gridster) from the second gridster. This is not a big issue because in the removeFromCache function the item is filtered.
But because the _items is undefined on the second gridster it throws an exception on line 256 in gridster.service.ts.
If I define _items on line 19 it works without a problem.

`_items: Array<GridListItem> = [];`

Best Regards

**Comment by swiety85** [comment]
Should be solved in v1.2.1

**Comment by gentle9** [comment]
Thank you very much for the fast fix.
