### ISSUE TITLE
Gridster+chart.js resizing issue

### ISSUE THREAD

**Issue by ashavyshakh** [swiety85/angular2gridster#189]
Hi,

I am using angular2 Gridster to make widget components . For this , I have used 3 rd party "chart.js" .
My problem is, when I resizing the widget, the canvas element does not fit into the widget. It is going out of the box. 
I want to fix my charts widget inside the grids & when ever  it resizing , it should retain position.
My code is given below
`<gridster class="gridster-wrapper" [options]="gridsterOptions"   *ngIf="widgets"
      [draggableOptions]="gridsterDraggableOptions">
      <div class="child"></div>
      <gridster-item class="gridster-widget" *ngFor="let widget of widgets" (change)="itemChanged(widget)"
                     [(x)]="widget.dashboardView.position.x" [(y)]="widget.dashboardView.position.y"
                     [(xSm)]="widget.dashboardView.position.xSm" [(ySm)]="widget.dashboardView.position.ySm"
                     [(xMd)]="widget.dashboardView.position.xMd" [(yMd)]="widget.dashboardView.position.yMd"
                     [(xLg)]="widget.dashboardView.position.xLg" [(yLg)]="widget.dashboardView.position.yLg"
                     [(xXl)]="widget.dashboardView.position.xXl" [(yXl)]="widget.dashboardView.position.yXl"
                     [(w)]="widget.dashboardView.position.w" [(h)]="widget.dashboardView.position.h">
                     <div class="row">
                      <canvas id="pie-chart" width="800" height="450"></canvas>
                     </div>
      </gridster-item>
    </gridster>`
`/*component ts*/
this.gridsterOptions = {
      lanes: 2, 
      direction: 'vertical',
      floating: true,
      dragAndDrop: true,
      resizable: true,
      useCSSTransforms: false, 
      swapping: true,
      responsiveOptions: [
        {
          breakpoint: 'sm',
          lanes: 3
        },
        {
          breakpoint: 'md',
          minWidth: 768,
          lanes: 4,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'lg',
          lanes: 6,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'xl',
          minWidth: 1800,
          lanes: 8,
          dragAndDrop: true,
          resizable: true
        }
      ]
    };

/*chart.js*/
new Chart(document.getElementById("pie-chart"), {
    type: 'pie',
    data: {
      labels: ["Africa", "Asia", "Europe", "Latin America", "North America"],
      datasets: [{
        label: "Population (millions)",
        backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
        data: [2478,5267,734,784,433]
      }]
    },
    options: {
      title: {
        display: true,
        text: 'Predicted world population (millions) in 2050'
      }
    }
});
`

**Comment by rudzikdawid** [comment]
some of chart liblaries need `resize` event on window object to call refresh/repaint methods.
For example chartis.js https://github.com/gionkunz/chartist-js/issues/1010
Maby we can extend the gridster options about `triggerResizeEvent` flag ?

**Comment by rudzikdawid** [comment]
You can simple trigger `resize` event using `(end)` callback
```
<gridster-item *ngFor="let widget of charts"
               (end)="refreshChart($event)"
               [(x)]="widget.x"
               [(y)]="widget.y"
               [(w)]="widget.w"
               [(h)]="widget.h">
...
</gridster-item>
```
and inside controller
```
refreshChart = function(event) {
   if (event && event.action === 'resize') {
      window.dispatchEvent(new Event('resize'));
   }
};
```

this solution work with `chartist.js` of cource you can call internal chart liblary method to repaint/refresh chart instead triggering `resize` event. 

If you want repaint/refresh your chart in the same time when you manipulate windgets you can use ` (start)="refreshChart($event)"` calback and inside `refreshChart` method you can use interval to repaint/refresh every 100ms or something. Then dont forget to cancel interval on (end) callback
