### ISSUE TITLE
Possible to track order sequence of grid items?

### ISSUE THREAD

**Issue by MaxSwank** [swiety85/angular2gridster#191]
The itemChange event gives alot of good data but I don't see anything related to something like array position of previous vs new when dragging items from one position to another.  I'd like to be able to send the order position data to a database but I don't see a clear way.  Thanks.

**Comment by swiety85** [comment]
Hi,
so what you would need is oldValue in change event object, do I understand right? e.g.
```js
{
    breakpoint: "lg",
    changes: ["x", "y"],
    item: {
        "x": 0,
        "y": 0,
        ....
    },
    oldValues: {
        "x": 1,
        "y": 2
    }
}
```

**Comment by MaxSwank** [comment]
Yes, exactly.  Some way to track to the previous value within the change event would be super helpful.  Thanks for the quick reply.
