### ISSUE TITLE
Controlling the intervals of the widget size

### ISSUE THREAD

**Issue by tssobe** [swiety85/angular2gridster#192]
Hi 

I would like a way to control the intervals when changing the size of the widget.

How can I do it?

Thanks

**Comment by swiety85** [comment]
Hi, what exactly you mean with intervals? Can you give some example?

**Comment by swiety85** [comment]
Do you mean min and max width and heigh? If yes, you have option to set it by [GridsterItem.options](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#gridsteritemcomponent).

**Comment by tssobe** [comment]
No,
Once resizing the widget I want the option to control in how much it resized.
For example, now when I resize it get bigger in 10px(for example). I want that instead of 10 it will be 20.
Is it possible?

**Comment by swiety85** [comment]
The size of items are aligned to the grid structure. When you start resizing, item will try always to align to nearest lane. If gird cell takes like 10px, it's not possible to prevent user to resize to 10px more or less.
If you want to have bigger "jumps" while resizing, maybe just reduce amount of lanes in your grid.
