### ISSUE TITLE
[Question] Is it possible to save and restore the full gridster state?

### ISSUE THREAD

**Issue by feco93** [swiety85/angular2gridster#195]
It would be nice if it is possible with this great component. If possible please provide code snippet.

**Comment by rudzikdawid** [comment]
it's very simple, you have to write few lines of `javascript/typescript`

**Comment by feco93** [comment]
Could you share with me the appropriate code snippet or example, or just the input and output properties?

**Comment by ishandeb** [comment]
@swiety85 It would be very helpful if you could provide a solution for to save and restore the full gridster state.

Thanks, In advance.

**Comment by rudzikdawid** [comment]
example http://dawid.ru/workspace/something
source: https://github.com/rudzikdawid/material2-start/tree/patients/src/app/workspace/something

to test: move widgets, resize widgets, **refresh browser page** `F5` or `Ctrl+Shift+R` 
after refresh your should see your changes.

in this example I use localstorage to keep widgets state.

## read data.
In this example I uses sync call which returns data mock. 
```
ngOnInit() {
  this.widgets$ = this.loadWidgets();
}
```
In real application widgets state should be taken from REST service (async call, $http).

## save data.
the best way to save widgets state is using: `(end)` Outputs.
```
(end)="saveWidgets()"
```
`(end)` callback fires after we stop moving/resizing widgets
```
saveWidgets() {
  window.localStorage['widgets-charts'] = JSON.stringify(this.widgets$.charts);
  window.localStorage['widgets-streams'] = JSON.stringify(this.widgets$.streams);
}
```
