### ISSUE TITLE
Change default height of gridster-container .

### ISSUE THREAD

**Issue by ashavyshakh** [swiety85/angular2gridster#197]
Hi,
Initially gridster-container has height of 636px. I have scrolling bar when i added one gridster Item.I need to remove unwanted scrolling. How can i adjust height of  gridster-container?
Thanks in advance.

**Comment by swiety85** [comment]
The gridster-container sets heigh dynamically. You can prevent gridster to reserve additional empty space below items by setting `shrink: true` in gridsterOptions.

**Comment by ashavyshakh** [comment]
Thank you ! its helped me.
