### ISSUE TITLE
Margin space is needed between two grids

### ISSUE THREAD

**Issue by ashavyshakh** [swiety85/angular2gridster#200]
Hi,
My gridsters do not have space between them. I would like to add space between then as per the demo shows. Could you please describe the css for that?

**Comment by swiety85** [comment]
Demo styles are defined in `.gridster-item-inner` class. You can find styles here:
https://github.com/swiety85/angular2gridster/blob/6799d06a76afce1efb6f16a345f1f4dd198c46b6/demo/src/styles.css#L49

**Comment by ashavyshakh** [comment]
It s not working , when i override this css in my local style.css file

**Comment by swiety85** [comment]
Provide me a Plunker example or something that I can reproduce your problem. Without any example I can not help you.

**Comment by ashavyshakh** [comment]
OK, Sorry for the inconvenience . I ve given my code below
`<gridster class="gridster-wrapper" [options]="gridsterOptions" *ngIf="widgets" [draggableOptions]="gridsterDraggableOptions" style="margin:10px">
      <gridster-item class="gridster-widget range"
      *ngFor="let widget of widgets;let i = index"
      (click)="activeIndex = i"
      [ngClass]="{ clicked : activeIndex === i }"
      (change)="itemChanged(widget)"
       [(x)]="widget.dashboardView.position.x"
       [(y)]="widget.dashboardView.position.y"
       [(xSm)]="widget.dashboardView.position.xSm"
       [(ySm)]="widget.dashboardView.position.ySm"
       [(xMd)]="widget.dashboardView.position.xMd"
       [(yMd)]="widget.dashboardView.position.yMd"
       [(xLg)]="widget.dashboardView.position.xLg"
       [(yLg)]="widget.dashboardView.position.yLg"
       [(xXl)]="widget.dashboardView.position.xXl"
       [(yXl)]="widget.dashboardView.position.yXl"
       [(w)]="widget.dashboardView.position.w"
       [(h)]="widget.dashboardView.position.h"
       [id]="widget._id">
        <div class="button-group" >
          <button class="delete-button" mat-icon-button color="primary" (click)="click_delete_widget(widget)">
                         <i class="material-icons vue-icon">delete</i><span matTooltip="delete widget" value="above"></span>
          </button>
          <button class="delete-button" mat-icon-button color="primary" (click)="click_edit_widget(widget)">
                         <i class="material-icons vue-icon">mode_edit</i>
          </button>
        </div>
        <div id="div-inner-active" **[innerHTML]**="widget.dashboardView.html | noSanitize" style="padding:0px"[style.width.px]="getWidth(widget._id)" [style.height.px]="getHeight(widget._id)">
        </div>
      </gridster-item>
    </gridster>`

- My html code is given above
-Currently I did not write any custom CSS

- In **[innerHTML]**  contents are chart.js, Imgaes 
-I tried   .gridster-item-inner { ... } in my component.css file but it did not worked.

-  gridster option I have set as given below
this.gridsterOptions = {
      lanes: 2, // how many lines (grid cells) dashboard has
      direction: 'vertical', // items floating direction: vertical/horizontal/none
      floating: true, // default=true - prevents items to float according to the direction (gravity)
      dragAndDrop: true, // possible to change items position by drag n drop
      resizable: true, // possible to resize items by drag n drop by item edge/corner
      useCSSTransforms: false, // Uses CSS3 translate() instead of position top/left - significant performance boost.
      swapping: true,
      shrink: false,
      outerMargin: true,
      // ResponsiveOptions can overwrite default configuration with any option available for specific breakpoint.
      responsiveOptions: [
        {
          breakpoint: 'sm',
          lanes: 3
        },
        {
          breakpoint: 'md',
          minWidth: 768,
          lanes: 4,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'lg',
          lanes: 6,
          dragAndDrop: true,
          resizable: true
        },
        {
          breakpoint: 'xl',
          minWidth: 1800,
          lanes: 8,
          dragAndDrop: true,
          resizable: true
        }
      ]
    };

**Comment by swiety85** [comment]
You must set `.gridster-item-inner` in `styles.css` in `/src`directory that is global for whole app.
In one of the next release I will provide a way to just style gridster in parent component css file.

**Comment by swiety85** [comment]
To style nested components in parent you have to use `ViewEncapsulation.None`.
