### ISSUE TITLE
Responsive view of dashboard is not detecting the correct breakpoint options

### ISSUE THREAD

**Issue by kmanikandanmca2008** [swiety85/angular2gridster#201]
**Problem statement:**
When I place the dashboard inside the div ( 50% width of my screen) it is not picking the correct breakpoint(md) instead it picks xl only.
But this is proper in full screen size also with resizing of window. Current breakpoint i'm taking from `GridsterComponentInstance.gridster.options` .

**Expected behaviour:**

Dashboard parent width size break point should be detected automatically.

I have attached two scenarios with screenshot with browser console.
screenshots:
![responsive_breakpoint](https://user-images.githubusercontent.com/16201678/36888499-c55fd104-1e1b-11e8-99b6-0bf623cb7d58.PNG)

![responsive_breakpoint2](https://user-images.githubusercontent.com/16201678/36888528-e0cf5270-1e1b-11e8-8269-90c1bc519c31.PNG)

**Comment by swiety85** [comment]
Breakpoints in gridster relates to window size (like in CSS) not to container size. If gridster container always proportionally shrink with window size (e.g. 50%), you can declare minWidth twice the size of the container and then behaviour will be the same.
I'm aware that this will not work when you have some more complex cases e.g. different container sizes depend on different responsive breakpoints in CSS, or some aside that will shrink the width of the main content when it's open. 
I will leave this issue as an enhancement task to provide configuration whether `minWidth` in `responsiveOptions` should relay on window size or gridster container size.

**Comment by HMubaireek** [comment]
I'd love to have this feature implemented.
