### ISSUE TITLE
drag & drop from different component

### ISSUE THREAD

**Issue by PeterDjukic** [swiety85/angular2gridster#208]
Hi 

i need help with dragging and doping of new widget 
In demo you have your draggable widget in same app.component how do i get it to work from outside component. 
menu.componetns --> widgets
 to 
dashboard.component  --> gridster

thaks

**Comment by swiety85** [comment]
Where do you import GridsterModule?

**Comment by PeterDjukic** [comment]
ok so i realize the module should be imported only once lets say in coreModule or AppModule but then i get error 'gridster' is not a known element:

**Comment by swiety85** [comment]
I noticed that this use case could be problematic. I will provide a fix for that in one of nearest release.

**Comment by PeterDjukic** [comment]
Thanx. Will have a look. I managed to do it thru service.

**Comment by prasad1791** [comment]
@PeterDjukic  I am doing same thing , my menu is in the side-bar. if i am placing both component in same html (menu and dashboard component ) then its working but placing it into different html then it's not working, can you share your code ?

**Comment by PeterDjukic** [comment]
Sure  
I am not using service anymore. Now I put the draggeditem into data of drag event and on emptyCellClik I read that data from that event.

This is how it works for me.  

In **menu component** I have a method that is called on dragstart 

_**onDrag**(menuItem, event) {
    event.dataTransfer.setData('gridItem', JSON.stringify(menuItem));
    event.dataTransfer.dropEffect = 'copy';
  }_

and in **dashboard component** i have gridster options configured like 
_....
      enableEmptyCellDrop: true,
      emptyCellDropCallback: this**.emptyCellClick**.bind(this),
..._

 **emptyCellClick**(event, item: GridsterItem) {
    const self = this;
    const data = event.dataTransfer.items; 

    for (let i = 0; i < data.length; i += 1) {
      if (data[i].kind === "string" && data[i].type.match("^griditem")) {
        // This item is the target node
        data[i].getAsString(function(gridsterItemData) {
          item.data = JSON.parse(gridsterItemData);
          gridsterItems.push(item);
        });
      }
    }
  } 

hope this helps you
