### ISSUE TITLE
Collision Resolving without Gravity doesn't work as expected

### ISSUE THREAD

**Issue by dennisheer** [swiety85/angular2gridster#209]
The collision resolving strategy doesn't work as expected when disabling floating (gravity) for the grid.

## Steps to Reproduce
1. Open the [demo](https://swiety85.github.io/angular2gridster/)

![image](https://user-images.githubusercontent.com/15670613/37601149-9c9492b6-2b89-11e8-8b98-84c553c1bc6f.png)
**Figure:** Demo layout as of 19.03.2018

2. Disable "Floating (gravity)" in the toolbar
3. Move the GridsterItem 1 to where the GridsterItem 2 starts (move GridsterItem 1 from position 0 x 0 to 1 x 0)

![image](https://user-images.githubusercontent.com/15670613/37600728-7165ae6e-2b88-11e8-8129-1be77edba289.png)
**Figure:** GridsterItems 1, 4 and 2 are overlapping

## Expected Behaviour
When moving GridsterItem 1 to where GridsterItem 2 starts: 

- GridsterItem 4 moves down two tiles
**or**
- GridsterItem 4 moves one tile to the left

**Comment by swiety85** [comment]
Hi,
I've also seen this bug. I will fix it as soon as possible.
Thanx for raporting

**Comment by swiety85** [comment]
Fix available in v1.3.3
