### ISSUE TITLE
Solve dragging issues when gridster is placed in "scrollable" elements

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#21]

**Comment by swiety85** [comment]
Solution available in v.0.6.6.

**Comment by speculees** [comment]
Hey,
I have a gridster component in scrollable div. However, when getScrollPositionFromParents function returns data it actually causes problems on my page. Works fine if i lock it to always 
`        return {
            scrollTop: 0,
            scrollLeft: 0
        };` 

Any idea why is that?
