### ISSUE TITLE
Resize Gridster dynamically 

### ISSUE THREAD

**Issue by dmend078** [swiety85/angular2gridster#211]
I know there is a way for doing this, but I haven't been able to do it. I have a left menu with the icons to drag. The problem is that I want to have the menu hidden, and when the user wants to add widgets, he opens the menu. The problem is that when the menu is open, it moves the <gridster> to the size, cutting some elements. This gets fixed as soon as I drop a new element. When I drop a new element I notice that the <gridster> gets calculated, and everything fix. So my question is, how can I make everything fit the screen when the menu is shown? 
Bonus question: How can I change the color of the shadow in the grid view when you are about to drop/dragging the item?
Thank you!

**Comment by kevinrstone** [comment]
I had the same problem with a hidden side menu not causing the grid to reflow. Unless there is a better way my solution is to call `reload()` on the gridster component as a `ViewChild`.

e.g.
`<gridster #gridster [options]="gridsterOptions">...</gridster>`
and
`@ViewChild("gridster") gridster: GridsterComponent;`

and when my menu changes calling this
`if (this.gridster) { gridster.reload(); }`

**Comment by dmend078** [comment]
I try that but still doesn't work. This is my code: 
Note: I am using the same css for the demo that you can download. 
<div  class="omnibar">
    <div class="toolbar" [@sideMenuAnime]="openClose">
			<div  *ngFor="let widget of widgetList">
			<div *ngIf="widget.InUse == false" gridsterItemPrototype  [config]="{helper: true}" [w]="widget.DefaultW" [h]="widget.DefaultH"
				(drop)="addWidgetFromDrag(gridster, $event, widget)"
				(enter)="over($event)"
				(out)="out($event)"
				class="gridster-item-prototype">
				<i [ngClass]='widget.Icon' ></i> <br>
			
				<div _ngcontent-uoe-1="" class="gridster-item-inner" style="width: 0;height: 0;">
					<div _ngcontent-uoe-2="" class="panel-heading">
						<h5 _ngcontent-uoe-2="" class="panel-title">{{widget.Title}}</h5>
					</div>
				</div>
			</div>
		</div>
</div>
<div class="main-content">

    <gridster  [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions" (reflow)="onReflow($event)"
              (optionsChange)="optionsChange($event)" #gridster1 class="dashboard">

        <gridster-item *ngFor="let widget of widgets; let indx = index" #itemComp
                       [options]="itemOptions"
                       [dragAndDrop]="widget.dragAndDrop" [resizable]="widget.resizable"
                       [(x)]="widget.x" [(y)]="widget.y"
                       [(xSm)]="widget.xSm" [(ySm)]="widget.ySm"
                       [(xMd)]="widget.xMd" [(yMd)]="widget.yMd"
                       [(xLg)]="widget.xLg" [(yLg)]="widget.yLg"
                       [(xXl)]="widget.xXl" [(yXl)]="widget.yXl"
                       [(w)]="widget.w" [(h)]="widget.h"
                       (change)="itemChange($event, gridster1, widget)"
					   >

            <div class="panel-heading">
                <h5 class="panel-title">{{ widget.title }}  <i class="delete-widget fa fa-times-circle" aria-
 hidden="true" (click)="remove($event,indx,gridster1)"></i></h5>
            </div>
            <div class="panel-body">
               (...)		
            </div>
        </gridster-item>
    </gridster>
</div>

**Comment by dmend078** [comment]
`<div *ngIf="!loading"  class="omnibar">

    <div class="toolbar" [@sideMenuAnime]="openClose">

			<div  *ngFor="let widget of widgetList">
			<div *ngIf="widget.InUse == false" gridsterItemPrototype  [config]="{helper: true}" [w]="widget.DefaultW" [h]="widget.DefaultH"
				(drop)="addWidgetFromDrag(gridster, $event, widget)"
				(enter)="over($event)"
				(out)="out($event)"
				class="gridster-item-prototype">
				<i [ngClass]='widget.Icon' [tooltip]='widget.Title'  style="
																			color:#29588e; font-size: 28px;
																			width: 100%;
																			height: 100%;
																			margin-top: 25%;
																			position: relative;"
				></i> <br>
			
				<div _ngcontent-uoe-1="" class="gridster-item-inner" style="width: 0;height: 0;">
					<div _ngcontent-uoe-2="" class="panel-heading">
						<h5 _ngcontent-uoe-2="" class="panel-title">{{widget.Title}}</h5>
					</div>
				</div>
			</div>
		</div>
</div>
<div class="main-content">

    <gridster  [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions" (reflow)="onReflow($event)"
              (optionsChange)="optionsChange($event)" #gridster1 class="dashboard">

        <gridster-item *ngFor="let widget of widgets; let indx = index" #itemComp
                       [options]="itemOptions"
                       [dragAndDrop]="widget.dragAndDrop" [resizable]="widget.resizable"
                       [(x)]="widget.x" [(y)]="widget.y"
                       [(xSm)]="widget.xSm" [(ySm)]="widget.ySm"
                       [(xMd)]="widget.xMd" [(yMd)]="widget.yMd"
                       [(xLg)]="widget.xLg" [(yLg)]="widget.yLg"
                       [(xXl)]="widget.xXl" [(yXl)]="widget.yXl"
                       [(w)]="widget.w" [(h)]="widget.h"
                       (change)="itemChange($event, gridster1, widget)"
					   >

            <div class="panel-heading">
                <h5 class="panel-title">{{ widget.title }}  <i class="delete-widget fa fa-times-circle" aria-hidden="true" (click)="remove($event,indx,gridster1)"></i></h5>
            </div>
            <div class="panel-body">
				<div *ngIf="searchShow == widget.fkWidgetId">
					<search></search>     					
				</div>
				<div *ngIf="recentShow == widget.fkWidgetId">
				<recent></recent>      					     					
				</div>
				<div *ngIf="notificationShow == widget.fkWidgetId">
						<notification></notification>					   					
				</div>
				<div *ngIf="delinquentShow == widget.fkWidgetId">
					<delinquent></delinquent>     					
				</div>
				<div *ngIf="portfolioShow == widget.fkWidgetId">
					<portfolio></portfolio>    					
				</div>
				<div *ngIf="pendingapprovalShow == widget.fkWidgetId">
					<pendingapproval></pendingapproval>    					
				</div>
				<div *ngIf="pastdueShow == widget.fkWidgetId">
					<past-due></past-due>  					
				</div>
				<div *ngIf="piechartShow == widget.fkWidgetId">
					<pie-chart></pie-chart>    					
				</div>
				<div *ngIf="barchartShow == widget.fkWidgetId">
					<bar-chart></bar-chart>   					
				</div>
				<div *ngIf="lateShow == widget.fkWidgetId">
					<lates></lates>
				</div>
				
            </div>

        </gridster-item>

    </gridster>
</div>`

**Comment by swiety85** [comment]
Hi, please write me more how you call `gridster.reload` - especially when the function is called.

**Comment by kevinrstone** [comment]
Are you familiar with the ViewChild pattern?
See: [https://angular.io/api/core/ViewChild](https://angular.io/api/core/ViewChild)

Once you have that set, it's just a matter of calling `this.gridster.reload()`, assuming you have named your ViewChild `gridster`. 

In my scenario I call `reload()` every time my menu opens, and every time it is closed. Depending on the timing (E.g. if you have any animations) you may need to call `setTimeout(() => { this.gridster.reload(); });` to make sure it is called after the window sizes have changed. I don't know what your situation is, but my menu opens from outside components, so I use Observable subscriptions to handle when to fire the `reload()` call. There are other patterns as well, but you can read about them here: [https://angular.io/guide/component-interaction](https://angular.io/guide/component-interaction) .


I don't know if this will help, but it's really as simple as this (of course all this assumes `reload()` is what you need to call to solve your problem).

```
@Component({
    selector: 'my-dashboard',
    template: `
        <gridster #gridster [options]="gridsterOptions">
           <gridster-item *ngFor="let widget of widgets">
           </gridster-item>
        </gridster>
    `,
})
export class MyDashboardComponent implements OnInit {

    @ViewChild("gridster") gridster: GridsterComponent;

    gridsterOptions: IGridsterOptions;
    widgets: any[] = [];

    constructor(
        // some service that can be used to communicate when menu toggles open/closed
        private myMenuCommService: MyMenuCommService,
    ) {}}

    ngOnInit() {

        this.gridsterOptions = { /* set gridster options */ };

        // menuToggleEvent triggered from some other component
        //   subscribe to event
        this.myMenuCommService.menuToggleEvent$.subscribe(() => {
            if (this.gridster) {
                 // reload gridster to trigger reflow
                 this.gridster.reload();
            }
        });
    }
}
```

**Comment by dmend078** [comment]
This really helps. 
I notice that I was keeping the width at 100% all the time, I need to reduce it when the toolbars opens. Thank you so much for the detail explanation. The timer helps a lot.
The other question will be about the shadow when you are dragging the widget. My shadow in the grid is transparent, I want it to be like a dark blue. How can I change it? Thank you.

**Comment by swiety85** [comment]
To apply styles for the dragging item you should use selector `.is-dragging .gridster-item-inner`. The styles should be defined in `styles.css/styles.scss` - the stylesheet that is global for the whole app. If you would put styles for gridster in component styles file it could not work because of view encapsulation.

**Comment by dmend078** [comment]
Thank you

**Comment by mrk9776** [comment]
To resize all items you can use `this.gridster.calculateLayoutDebounce();` method.
