### ISSUE TITLE
Allow fixed elements in grid

### ISSUE THREAD

**Issue by helldog136** [swiety85/angular2gridster#22]
There should be a parameter (fixed for example) in grid-item that makes it not draggable by the user while the others are still draggable.

for example you could write
<grid-item [x]="x" ... [h]="h" [fixed]="true"></grid-item>

Sorry it's more a suggestion than an issue :/

**Comment by swiety85** [comment]
Good suggestion. 👍 There is already a plan to make this functionality but it's called "pin". :-)
It's good to have it on issue list.

**Comment by swiety85** [comment]
Done in v.0.6.0

**Comment by Pennywise83** [comment]
Hi,
I  can't find a way to use this feature since it is not documented. Could you provide a simple example please?

**Comment by swiety85** [comment]
Hi,
for disabling dragging of single item you need to use `[dragAndDrop]` attribute, that expects boolean value. If value is false item will not be possible to move. Example:
```js
<gridster ...>
        <gridster-item *ngFor="..." [dragAndDrop]="widget.dragAndDrop">
           ...
       </gridster-item>
</gridster>
```
I will update documentation soon. Thanks for info!
