### ISSUE TITLE
Error on start drag in Prototype Gridster-inside-gridster branch

### ISSUE THREAD

**Issue by richardlnnr** [swiety85/angular2gridster#226]
This error occurs sometimes when I click in a Prototype item and start the drag.
I'm using the 123-Gridster-inside-gridster branch.
The bug is not easy to reproduce.

![image](https://user-images.githubusercontent.com/6029690/38500088-c8e3504e-3bdf-11e8-90ab-2bb35be94d89.png)

![image](https://user-images.githubusercontent.com/6029690/38503556-c2273bae-3be8-11e8-8b6c-333b747c6689.png)

**Comment by swiety85** [comment]
Can you please verify if the problem is not reproducible in branuch: `226-Error-on-start-drag-in-Prototype-Gridster-inside-gridster-branch`

**Comment by swiety85** [comment]
Should be fixed in v1.5.0.

**Comment by richardlnnr** [comment]
Sure, I'll test it
