### ISSUE TITLE
Gridster option Floating and Direction not allow drag in any position

### ISSUE THREAD

**Issue by richardlnnr** [swiety85/angular2gridster#228]
It's not possible to drag a element in any position.
The drag only enable the first or next grid line.
Is it possible to enable all rows to drag a element?

![verticalnofloating](https://user-images.githubusercontent.com/6029690/38571955-3fa94f10-3cc8-11e8-89ce-2955c6356270.gif)

![nonefloating](https://user-images.githubusercontent.com/6029690/38571977-4eb03618-3cc8-11e8-84bc-56c710455281.gif)

![nonenofloating](https://user-images.githubusercontent.com/6029690/38572018-5c2958ce-3cc8-11e8-8a25-667296ba5d00.gif)

**Comment by swiety85** [comment]
Should be fixed in v1.5.0.

**Comment by richardlnnr** [comment]
That's work very well, Thank you.
