### ISSUE TITLE
Nothing is displayed when followed the exact tutorial steps

### ISSUE THREAD

**Issue by tofiqquadri** [swiety85/angular2gridster#236]
I followed the exact tutorial steps by creating a new Angular project.

After that following minimalistic configuration:

<gridster [options]="gridsterOptions" [draggableOptions]="{ handlerClass: 'panel-heading' }">

  <gridster-item *ngFor="let widget of widgets" 
                 [(x)]="widget.x" [(y)]="widget.y" [(w)]="widget.w" [(h)]="widget.h">
      
  </gridster-item>

</gridster>
Gridster configuration can be defined as follows (more info here):

widgets: Array<any> = [...];
gridsterOptions = {
  lanes: 5, // how many lines (grid cells) dashboard has
  direction: 'vertical', // items floating direction: vertical/horizontal
  dragAndDrop: true, // possible to change items position by drag n drop
  resizable: true // possible to resize items by drag n drop by item edge/corner
  useCSSTransforms: true, // improves rendering performance by using CSS transform in place of left/top
};

I tried to run the application but it gives a blank screen. Let me know what could be the possible reasons.

**Comment by swiety85** [comment]
Hi, do you have any errors in console?
Does the DOM is generated correctly - gridster-item components has `style` attribute with `width`, `height`, `transform`?
If yes, then most probably you have a problem with CSS. What is the height of the `gridster` element?

**Comment by MohamedSaydSaleh** [comment]
Hi @tofiqquadri ,
You may need to add some style to gridster  item to show border to ensure Dom has been rendered well, <gridster-item style="border:solid"
and also I have replaced widgets: Array = [...]; with suitable list with widgets,
for me I replaced it with list exist in demo sample to test control before usage.
I hope this may help you or any other developer
I tested with Asp.net Core with Angular2 and it works fine till now

**Comment by tofiqquadri** [comment]
Hi Mohamed Sayed, 
Thank you for the reply I was able to resolve the issue thanks once again. 

Sent from Yahoo Mail on Android 
 
  On Thu, 3 May 2018 at 10:58 pm, MohamedSaydSaleh<notifications@github.com> wrote:   
Hi @tofiqquadri ,
You may need to add some style to gridster item to show border to ensure Dom has been rendered well, <gridster-item style="border:solid"
and also I have replaced widgets: Array = [...]; with suitable list with widgets,
for me I replaced it with list exist in demo sample to test control before usage.
I hope this may help you or any other developer
I tested with Asp.net Core with Angular2 and it works fine till now

**Comment by tofiqquadri** [comment]
@MohamedSaydSaleh 

Yes, I use the code from the Demo is there any issue with that? Let me in case it may cause some issue during production.

Thank you
