### ISSUE TITLE
No bottom grid lines if backgroundColor is not default

### ISSUE THREAD

**Issue by galvakojis** [swiety85/angular2gridster#237]
![workspace 1_470](https://user-images.githubusercontent.com/17315578/38865037-4e470346-4245-11e8-869c-587cd1f7e7b8.png)

if i change `lines.backgroundColor: white` none of bottom gridlines is displayed
i think this line
` linear-gradient(to right, ${linesColor} ${linesWidth}px, ${linesBgColor} ${linesWidth}px),`
need to be changed to this:
 linear-gradient(to right, ${linesColor} ${linesWidth}px, 'transparent' ${linesWidth}px),

**Comment by swiety85** [comment]
Hi,
`lines.backgroundColor` is optional option. If it will not be set, then `transparent` will be applied, as you suggested.
