### ISSUE TITLE
Cannot touch->click buttons inside drag handler

### ISSUE THREAD

**Issue by kevinrstone** [swiety85/angular2gridster#239]
I am not sure if there is a solution to this. We have buttons in our `panel-heading`s (E.g. an icon button to remove the panel) and they cannot be clicked on touch devices. The touch event is cancelled as part of the drag handling functions in angular2gridster, which means the subsequent click event is never fired. 

Is there a good way to work around this problem of buttons as children inside the drag handler class?

I am thinking maybe there isn't a way to allow this, since you obviously don't want other touch behaviors going on during dragging.

**Comment by swiety85** [comment]
I see the problem. It's fixable. I will provide soon.

**Comment by PodeMarut** [comment]
May be this help.
I have a problem and my workaround is install hammerjs and use (tap) instead (click).
