### ISSUE TITLE
Listeners on grid-items

### ISSUE THREAD

**Issue by helldog136** [swiety85/angular2gridster#24]
At the moment i don't see any way to listen for drag, drops, over and outs on grid-items. Only on prototypes :/

Did i miss something?

**Comment by swiety85** [comment]
Currently you can register on "x", "y", "w", "h" change. It will be two way binded in new release.
If you wish to have some more specific events on gridster-item, write me a list with explanations. I will consider implement them before new release.

Dragging out is not possible for now - gridster-item will try to be placed in most accurate position in board while dragging outside - placeholder is showing the position.
There is a plan to drag and drop items between different boards (and then such event would be needed), but what is your plan for this event?

**Comment by helldog136** [comment]
The projec i'm currently working on is an interface to create schedules.
The goal is to put kind of a <table> element but with grid items that you can swap (ie the element in 0,3 goes in 2,3 and 2,3 goes in 0,3) The only way i see this can be done is by listening to the drag of cell 0,3, registering x and y and when the drop is done, cancel it and change the data structure... 
I know it's very ugly but i'm a big newbie in angular and i didn't find any library that does that easily...

**Comment by swiety85** [comment]
If I understand it right, only "x" position will change, right? Events on position change are broken now (#16) but it will be fixed with release 0.5.0 next week.
Then you can use:
`<gridster-item [x]="item.x" (xChange)="itemChanged(item, $event)"></gridster-item>`
or
`<gridster-item [(x)]="item.x"></gridster-item>`
Then "x" property of "item" object will be automatically updated  on drop to new position.

Would it be enough?

**Comment by helldog136** [comment]
Yes it think so :-)

**Comment by swiety85** [comment]
v. 0.5.0 is ready. Events for position change should work now.

**Comment by swiety85** [comment]
in version 0.5.0 build code was broke therefore events for position and resize was not called ( #8 ).
Now it's fixed with version 0.5.1
