### ISSUE TITLE
Compilation Error on using the Gridster with angular 5

### ISSUE THREAD

**Issue by princevg** [swiety85/angular2gridster#244]
![image](https://user-images.githubusercontent.com/1523806/39519844-0acf1ef4-4e26-11e8-8941-ebb9bf5a1e5c.png)

Hi Sweity

Hope you are doing well. And I have used the awesome gridster in my dashboard with angular 2 it worked fine for me. On upgrading My application to angular 5 It was getting an error which you can see in the attached image

Thanks in advance
Prince Gracy

**Comment by swiety85** [comment]
Please check v5.0.0
