### ISSUE TITLE
On resizing the widgets and dragging them to change position initializes the element to false state

### ISSUE THREAD

**Issue by tofiqquadri** [swiety85/angular2gridster#245]
Hi,

When I try to resize the widget and change its position it displays this message in the console log: 

onReflow 
{isInit: false, gridsterComponent: GridsterComponent}
gridsterComponent
:
GridsterComponent {zone: NgZone, gridsterPrototype: GridsterPrototypeService, optionsChange: EventEmitter, ready: EventEmitter, reflow: EventEmitter, …}
isInit
:
false
__proto__
:
Object

And the widget disappears from the grid. Let me know what's the possible reason and how to fix it. 

Thank you

**Comment by swiety85** [comment]
Hi,
the console.log with "onReflow" is part of the [demo app component](https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.ts#L129).
Can I reproduce this issue on demo app? Please write detailed steps.
Thx!

**Comment by tofiqquadri** [comment]
Hi @swiety85 

Yes, I use the code sample from the demo and you will be able to reproduce the issue if you resize the widget and move it towards the container boundaries.

Let me know if you need additional details from my side.

Thank you for the support.

**Comment by swiety85** [comment]
I can not reproduce this problem on the demo app. Question for me is `reflow` event that is fired when you reposition the widget. This event is fired on following cases:
* on component init
* on gridster option.lanes change
* on window resize
On demo page `reflow` is also triggered after resizing by a button in the widget. 
Do you use resize by button?
I need more details to reproduce your problem.

**Comment by tofiqquadri** [comment]
Issue Solved.
