### ISSUE TITLE
Enable/Disable Drag&Drop

### ISSUE THREAD

**Issue by AlMuIssues** [swiety85/angular2gridster#25]
Hello,
how can I enable/disable drag&drop, for example with a toggle button. I've tried:
 --> to change dragAndDrop parameter ( IGridsterOptions )
--> to change handlerClass ( IGridsterDraggableOptions )
but nothing change the drag&drop functionality.

**Comment by swiety85** [comment]
I will try to deliver fix this week with new release.

**Comment by swiety85** [comment]
Please check v. 0.5.0. You can check how to enable/disable drag and resize in demo. I will also soon provide more detailed documentation.
I will appreciate some feedback info.

**Comment by swiety85** [comment]
It's possible since v. 0.5.0 to switch dragging on/off by calling on component instance:
`gridster.setOption('dragAndDrop', true/false);`

Resize:
`gridster.setOption('resizable', true/false);`
