### ISSUE TITLE
Gridster container won't resize to full width

### ISSUE THREAD

**Issue by miloskovacevic** [swiety85/angular2gridster#26]
Problem exists when i open inspect element console and i load the application.
After loading, gridster is adjusted to current width of screen, but when i close the inspect element
console, gridster stays with the same width. You can see this at your demo page https://swiety85.github.io/angular2gridster/.

Here are my printscreens:
![gridster_inspect](https://cloud.githubusercontent.com/assets/10956715/24951032/516343be-1f73-11e7-8a12-86943c6d7111.png)
![gridster](https://cloud.githubusercontent.com/assets/10956715/24951029/4c51d674-1f73-11e7-8b9f-a6a808c3ad00.png)

**Comment by swiety85** [comment]
Responsive behaviour can be easily applied by your own. Look on suggested solution in #17 issue.
In future I will create dedicated configuration for this.

**Comment by miloskovacevic** [comment]
Thank you!
