### ISSUE TITLE
posx and posy property binding not working

### ISSUE THREAD

**Issue by princevg** [swiety85/angular2gridster#262]
Hi Sweity

The property binding of x and y is not working. it is not taking from the JSON At all. eventhough the w and h are working. could you please help me on that?

thanks

**Comment by swiety85** [comment]
Problem with bindings position is solved in v5.0.4 (for Angular 5) and v6.0.1 (for Angular 6).
Please bear in mind, that when you use responsiveOptions you should use responsive position bindings (xSm, ySm, xMd, yMd ...). This is often mistaken.
