### ISSUE TITLE
Scroll error after updating to version 4.x

### ISSUE THREAD

**Issue by davidkr1** [swiety85/angular2gridster#264]
After updating from version 1.5.2 to 4.0.0 app stopped working. Something is wrong with drag and drop dunctionality. I get this error:

![image](https://user-images.githubusercontent.com/31256022/42155157-ed486be6-7de7-11e8-81bc-6d8fb0c2da0d.png)

**Comment by swiety85** [comment]
It seems that you don't pass any config for `draggableOptions`.
As a quick fix please set an empty object to `draggableOptions` attribute:
```html
  <gridster [draggableOptions]="{}" ...>...</gridster>
```
That should solve the problem for now.
The problem will be fixed in the component soon.

**Comment by swiety85** [comment]
Fixes are provided for Angular 5 - v5.0.5 and for Angular 6 - v6.0.2
