### ISSUE TITLE
Select or Drop Down is not working inside a Gridster

### ISSUE THREAD

**Issue by mayuranjan** [swiety85/angular2gridster#265]
We are trying to create a drop-down or select component inside Gridster, but we are unable to select any value. Even though the drop-down is enabled.

`<select _ngcontent-c8="" class="form-control" name="dropdown0">
                    <option _ngcontent-c8="" value="0">Select</option>
                    <option ngcontent-c8="" value="Female">Female</option><option ngcontent-c8="" value="Male">Male</option>
                </select>`

**Comment by swiety85** [comment]
Which version do you use? Does it happen for all browsers?

**Comment by Shilpithahs** [comment]
We tried with Chrome and Mozilla browser and we are using "0.6.9" version of angular2gridster.

**Comment by swiety85** [comment]
Can't you upgrade to newer version? This problem should be solved there. Which version of angular do you use?

**Comment by Shilpithahs** [comment]
I tried upgrading to a new version "angular2gridster": "^5.0.2" and Angular to 6.0.0. But I'm getting an error like  "Cannot find module 'angular2gridster'".

**Comment by swiety85** [comment]
If you use Angular 6, please install v6.0.1:
```
npm i --save angular2gridster@6.0.1
```
Latest tag is broken - it installs by default broken v5.0.2.
I will fix it soon. Sorry for inconveniences.

**Comment by swiety85** [comment]
Problem with the latest tag is solved. You can use `npm i --save angular2gridster` to install the newest version for Angular 6.

**Comment by swiety85** [comment]
For Angular 5 you can use v5.0.4 and for Angular 6 you can use v6.0.1. Please use those versions explicitly in package.json.

**Comment by JaiKumaresh** [comment]
Inside of gridster Selectbox did not open in my project.`"@angular/cli": "^7.1.4""angular-gridster2": "^8.2.0"`
Can you help me..??

**Comment by ashwanizsktm** [comment]
Normal select option is not opening in gridser item, however ng-select is getting opened. I want to implement the normal select, which is not even opening,
