### ISSUE TITLE
Scrolling while dragging

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#27]
When widgets don't fit screen and we want to move element from top to bottom (below viewport) the viewport should scroll while dragging. 
Scrolling should start when dragged element enters window edge or optionally defined window margin.
Should work in both: vertical and horizontal direction.

**Comment by deependhamecha** [comment]
Waiting for this feature to be merged. Can you please merge as soon as possible?

**Comment by swiety85** [comment]
Hi, this and all others will be merged and released in the end of this week.

**Comment by swiety85** [comment]
Should work by default since v1.0.0-alfa. Possible config you can find in [wiki](draggableOptions) in `draggableOptions`.
