### ISSUE TITLE
 Can't bind to 'config' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by Pravin-Chopde** [swiety85/angular2gridster#270]
Can't bind to 'config' since it isn't a known property of 'div'. ("  <div class="toolbar">
          <div class="widgetbar">
            <div ngxGridsterItemPrototype [ERROR ->][config]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
         "): ng:///AppModule/DashboardCreatorComponent.html@6:42
Can't bind to 'w' since it isn't a known property of 'div'. ("        <div class="widgetbar">
            <div ngxGridsterItemPrototype [config]="{helper: true}" [ERROR ->][w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" ["): ng:///AppModule/DashboardCreatorComponent.html@6:68
Can't bind to 'h' since it isn't a known property of 'div'. ("<div class="widgetbar">
            <div ngxGridsterItemPrototype [config]="{helper: true}" [w]="1" [ERROR ->][h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2""): ng:///AppModule/DashboardCreatorComponent.html@6:76
Can't bind to 'wSm' since it isn't a known property of 'div'. ("ss="widgetbar">
            <div ngxGridsterItemPrototype [config]="{helper: true}" [w]="1" [h]="1" [ERROR ->][wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2" (drop)="): ng:///AppModule/DashboardCreatorComponent.html@6:84
Can't bind to 'hSm' since it isn't a known property of 'div'. ("bar">
            <div ngxGridsterItemPrototype [config]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [ERROR ->][hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2" (drop)="addWidget"): ng:///AppModule/DashboardCreatorComponent.html@6:94
Can't bind to 'wMd' since it isn't a known property of 'div'. ("        <div ngxGridsterItemPrototype [config]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [ERROR ->][wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2" (drop)="addWidgetFromDrag(g"): ng:///AppModule/DashboardCreatorComponent.html@6:104
Can't bind to 'hMd' since it isn't a known property of 'div'. ("iv ngxGridsterItemPrototype [config]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [ERROR ->][hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2" (drop)="addWidgetFromDrag(gridster, $"): ng:///AppModule/DashboardCreatorComponent.html@6:114
Can't bind to 'wLg' since it isn't a known property of 'div'. ("sterItemPrototype [config]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [ERROR ->][wLg]="2"
              [hLg]="2" [wXl]="3" [hXl]="2" (drop)="addWidgetFromDrag(gridster, $event,1,'W"): ng:///AppModule/DashboardCreatorComponent.html@6:124
Can't bind to 'hLg' since it isn't a known property of 'div'. ("g]="{helper: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [ERROR ->][hLg]="2" [wXl]="3" [hXl]="2" (drop)="addWidgetFromDrag(gridster, $event,1,'Workorder Part List')" (e"): ng:///AppModule/DashboardCreatorComponent.html@7:14
Can't bind to 'wXl' since it isn't a known property of 'div'. ("r: true}" [w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [ERROR ->][wXl]="3" [hXl]="2" (drop)="addWidgetFromDrag(gridster, $event,1,'Workorder Part List')" (enter)="ove"): ng:///AppModule/DashboardCreatorComponent.html@7:24
Can't bind to 'hXl' since it isn't a known property of 'div'. ("[w]="1" [h]="1" [wSm]="1" [hSm]="1" [wMd]="2" [hMd]="1" [wLg]="2"
              [hLg]="2" [wXl]="3" [ERROR ->][hXl]="2" (drop)="addWidgetFromDrag(gridster, $event,1,'Workorder Part List')" (enter)="over($event)""): ng:///AppModule/DashboardCreatorComponent.html@7:34
Can't bind to 'config' since it isn't a known property of 'div'. ("
            </div>

            <div ngxGridsterItemPrototype [ERROR ->][config]="{helper: true}" [w]="4" [h]="4" (drop)="addWidgetFromDrag(gridster, $event,2,'Part List')"
"): ng:///AppModule/DashboardCreatorComponent.html@18:42
Can't bind to 'w' since it isn't a known property of 'div'. ("
            </div>

            <div ngxGridsterItemPrototype [config]="{helper: true}" [ERROR ->][w]="4" [h]="4" (drop)="addWidgetFromDrag(gridster, $event,2,'Part List')"
              (enter)="ove"): ng:///AppModule/DashboardCreatorComponent.html@18:68
Can't bind to 'h' since it isn't a known property of 'div'. ("
            </div>

            <div ngxGridsterItemPrototype [config]="{helper: true}" [w]="4" [ERROR ->][h]="4" (drop)="addWidgetFromDrag(gridster, $event,2,'Part List')"
              (enter)="over($event"): ng:///AppModule/DashboardCreatorComponent.html@18:76
Can't bind to 'config' since it isn't a known property of 'div'. ("
            </div>

            <div ngxGridsterItemPrototype [ERROR ->][config]="{helper: true}" [w]="4" [h]="2" (drop)="addWidgetFromDrag(gridster, $event,3,'Quote List')""): ng:///AppModule/DashboardCreatorComponent.html@28:42
Can't bind to 'w' since it isn't a known property of 'div'. ("
            </div>

**Comment by nehete-ruchi** [comment]
Hey,
I am getting same error...
What is the resolution for this?

**Comment by Pravin-Chopde** [comment]
What's you angular version??
I got this resolved updating to 6.02...
