### ISSUE TITLE
Getting OldValues empty on gridster item change event

### ISSUE THREAD

**Issue by dipankar-datta** [swiety85/angular2gridster#273]
When we swap positions of two gridster  items placed horizontally, the second event fired on change event does not have oldValues, where the first fired event has. This is reproducible  in the demo page as well.

![ag2gridsterissue](https://user-images.githubusercontent.com/32102567/42812413-2e5d3e00-89db-11e8-9148-003880a4d4d6.JPG)

Also reproducible by moving gridster items horizontally. Especially when a widget is move from left to right horizontally.

I'm using angular2gridster 5.0.2 with Angular 5.

**Comment by dipankar-datta** [comment]
Also reproducible by moving gridster items horizontally.

**Comment by swiety85** [comment]
I can confirm this bug. I will fix it ASAP.
Thx for reporting!

**Comment by swiety85** [comment]
Fixes are provided for Angular 5 - v5.0.5 and for Angular 6 - v6.0.2
