### ISSUE TITLE
GridsterItem shadow on dragging

### ISSUE THREAD

**Issue by davidkr1** [swiety85/angular2gridster#283]
Hi,

I have a problem in ver. 4.0.0. Despite setting gridsterItemPrototype [h] and [w] size of the shadow, it is not changing properly. It is always a square (my setting are [w]="2" [h]="1" and on grid there is a square 2x2). After dropping the size is correct, but this shadow is really annoying.

Please note that in ver 1.5.2 everything was working good.

**Comment by swiety85** [comment]
Please provide me at least a code with your Gridster configuration and html with gridsterItemPrototype.
Best would be to have steps to reproduce on demo app or working example with this problem:
[![Edit Angular2gridster demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w77q2rqll)

**Comment by davidkr1** [comment]
I'm pasting code for prototype and gridster configuration.

`<div gridsterItemPrototype [config]="{helper: true}" [w]="2" [h]="1"
        (drop)="addWidgetFromDrag($event, 'label')"
        class="gridster-item-prototype">
        <div class="input-mat form-control ng-pristine widget">Label</div>
    </div>`

`getGridsterOptions(): {
    return {
      lanes: 12,
      direction: 'vertical',
      floating: false,
      dragAndDrop: true,
      resizable: true,
      widthHeightRatio: 2,
      shrink: true,
      responsiveView: true,
      responsiveDebounce: 500,
      useCSSTransforms: true
    };
  }`

**Comment by davidkr1** [comment]
Hi again,

I found a mistake in your code causing this "shadow effect error".

Mistake is in GridListItem.js file. I'm pasting code:

`GridListItem.prototype.getHProperty = function (breakpoint) {
        if (this.itemPrototype) {
            return this.itemPrototype[GridListItem.H_PROPERTY_MAP[breakpoint]] ?
                GridListItem.H_PROPERTY_MAP[breakpoint] : 'w';
        }
        var item = this.getItem();
        var responsiveSizes = item.gridster && item.gridster.options.responsiveSizes;
        if (breakpoint && responsiveSizes) {
            return GridListItem.H_PROPERTY_MAP[breakpoint];
        }
        else {
            return 'h';
        }
    };`

There is `GridListItem.H_PROPERTY_MAP[breakpoint] : 'w';`
Should be: `GridListItem.H_PROPERTY_MAP[breakpoint] : 'h';`

Please for correction.
