### ISSUE TITLE
[Question] Is there a way to increase the gap between widgets ?

### ISSUE THREAD

**Issue by dipankar-datta** [swiety85/angular2gridster#284]
Hi Damian,

Is there a way we can increase the gap between the widgets ?

**Comment by swiety85** [comment]
Sure, just use CSS. In the demo app you can define margins by setting `top`, `right`, `bottom`, `left` properties on `.gridster-item-inner` element. In the [demo app](https://github.com/swiety85/angular2gridster/blob/master/src/app/app.component.css#L127) it's 5px.

**Comment by leye0** [comment]
🤷‍♂left, top, right, bottom do nothing. Margin property works. Thoughts?
