### ISSUE TITLE
just a few questions

### ISSUE THREAD

**Issue by essadji** [swiety85/angular2gridster#289]
1) is there a reason your example code copies the widgets to a new variable to display them?
2) is there an easy way to make the resize handle larger?

**Comment by swiety85** [comment]
Hi,
Ad 1. I'm not sure which code do you mean. Please send a link to the code that you mean.
Ad 2. It's enough to just overwrite some CSS by selectors defined here: https://github.com/swiety85/angular2gridster/blob/master/projects/angular2gridster/src/lib/gridster-item/gridster-item.component.ts#L60-L131

**Comment by essadji** [comment]
Thanks again. For now I just left the cloning out and so far it still behaves perfectly. I can revisit this issue, should it start to cause trouble.
I do have another question, however: I keep getting random borders on my widgets, even though I only use borders when dragging. The borders are usually not full borders, only 1-3 sides seem to appear. And even those borders have different widths on the different sides of a single cell. Any ideas?

**Comment by swiety85** [comment]
It seems to be a rendering issue. I'm not sure if I understand your problem right. Please send me the styles you have for the widgets with borders maybe then I can help you.
