### ISSUE TITLE
error TS2307

### ISSUE THREAD

**Issue by sw-ms-mohitsolanki** [swiety85/angular2gridster#292]
ERROR in src/app/app.component.ts(2,80): error TS2307: Cannot find module 'angular2gridster'.
src/app/app.module.ts(1,32): error TS2307: Cannot find module 'angular2gridster'.

I had download code from Master branch and install npm, after that just try to run (ng serve) but i am getting above errors.
please let me know how to solve this error.

**Comment by swiety85** [comment]
Which version do you use?

**Comment by swiety85** [comment]
The project is configured (tsconfig.json) to use angular2gridster code as a library. 
To run the demo app by `npm start` you need to call first `npm run build` that will build the angular2gridster library.
If you would like to use this project as a base app and install angular2gridster from the npm, you would have to remove "paths" from tsconfig.json.
Personally, I would suggest to just create an empty project by angular cli and then copy only the app module.
