### ISSUE TITLE
Productive build still fails with use of v5.0.5 in lazy loaded module

### ISSUE THREAD

**Issue by gschafra** [swiety85/angular2gridster#295]
Although confirmed and marked as close in #286 , I've still got the same issue with v5.0.5 used in a lazy loaded moduel in prod-build:

> ERROR in Error during template compile of 'DashboardModule'
>   Function calls are not supported in decorators but 'GridsterModule' was called.

Build command: 

> ng build --prod

Module lazy loaded as defined in app-routing.module.ts
```typescript
const appRoutes: Routes = [
	{
		path: 'portal',
		component: PortalComponent,
		canActivate: [AuthenticatedGuard],
		canActivateChild: [AuthenticatedGuard],
		children: [
			{
				path: 'dashboard',
				loadChildren: 'app/dashboard/dashboard.module#DashboardModule'
			},
```
... and import of GridsterModule done in dashboard.module.ts
```typescript
import { GridsterModule } from 'angular2gridster';
...
@NgModule({
	imports: [
		SharedModule,
		DashboardRoutingModule,
		GridsterModule.forRoot(),

```
Additionally the IDE (PHPStorm) shows the ts-lint error:

> ng: 'gridster-item' is not a known element: 
> 1. If 'gridster-item' is an Angular component, then verify that it is part of this module. 
> 2. If 'gridster-item' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message

What am I doing wrong?

Specs:
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/cli": "^1.6.6",
    "@angular/compiler-cli": "^5.2.9",

Besides... with angular2gridster@1.5.3 (and without .forRoot() of course) everything is working fine.

**Comment by swiety85** [comment]
Please check v5.0.6

**Comment by gschafra** [comment]
Works like a charm. Thanks a lot!
