### ISSUE TITLE
loading dynamic widget position from database

### ISSUE THREAD

**Issue by salmanx** [swiety85/angular2gridster#296]
Hi how can I load dynamic position for every widget? I have saved position x, y  which mainly indicates cell and translate value for  x and y position which mainly for css transformation. but when data is loaded form server translated value for css transformation is not working. here is my code snippet - 
<gridster-item 
	*ngFor="let table of tables" 
	#itemComp 
	[options]="itemOptions" 
	[dragAndDrop]=true
	[resizable]=true
	[(x)]="table.css_axis_x" 
	[(y)]="table.css_axis_y"
	[ngStyle]="{'transform': 'translate(' + table.css_translate_x + 'px, ' + table.css_translate_y + 'px)'}"
	(change)="itemChange($event, table)">
</gridster-item>

**Comment by swiety85** [comment]
Hi, which version of Gridster do you use?
You should not use style transform for positioning the items in the grid. Gridster is doing it for you out of the box. If you want to use CSS transform and not the width and height properties, just set `useCSSTransforms: true` in the gridster options.

**Comment by tdmitchal** [comment]
When I try to load a widget during Initialization, lets say X=780, it still takes it back to "0".  The item change event is triggered.
