### ISSUE TITLE
element.style is undefined error while dragging widget outside browser window (firefox only)

### ISSUE THREAD

**Issue by 175451** [swiety85/angular2gridster#298]
angular2gridster Version 6.0.2
firefox version 62.0.2
There is a console error and view crush when the mouse drop event happens outside of the browser widow. Can be reproduced on the demo page.
![firefox_bug_crushing_github](https://user-images.githubusercontent.com/9253652/45996297-02d8e480-c09c-11e8-8c3e-643c0b8c73e0.gif)
![obraz](https://user-images.githubusercontent.com/9253652/45996165-762e2680-c09b-11e8-9bed-db742aaf5ef8.png)

**Comment by brieucthomas** [comment]
Hi, this issue is still present on the demo page and on the `v6.0.3` release.

**Comment by 175451** [comment]
@brieucthomas That's true. However, if you need a really quick fix, add:
```
if(!document['style'] && document.documentElement){
 document['style'] = document.documentElement.style
}
```
somewhere in your app/module initializer.
Not the most beautiful solution ever but does the trick.

**Comment by swiety85** [comment]
Please check v6.0.4

**Comment by brieucthomas** [comment]
thanks @swiety85, it works.
