### ISSUE TITLE
gridster-item options

### ISSUE THREAD

**Issue by dipcore** [swiety85/angular2gridster#30]
Nice feature would be to have options per item:

<gridster-item *ngFor="let item of options.items; let indx = index" [(x)]="item.x" [(y)]="item.y" [(w)]="item.w" [(h)]="item.h" **[options]="item.options"**>

Or maybe change item attributes to 

<gridster-item *ngFor="let item of options.items; let indx = index" [options]="item.options"(change)="change(params)" (ready)="ready(params)" (more_events_here)="some_event(params)">
and store x,y,w,h in the item options.

Some options may be similar to global ones, ie 
```
{
   dragAndDrop: false,
   resizable: false
   ...
}
```
I believe it will solve https://github.com/swiety85/angular2gridster/issues/22 and gives some flexibility. For instance you can disable dragAndDrop for a single item (pinned) but keep it resizable, or opposite.

We could even have resizableOptions which works when resizable is set to true:
```resizableOptions: {left: true, right: true, top:false, bottom: false}``` That allows to make items resizeble to some directions, ie horizontally or vertically only etc.

**Comment by swiety85** [comment]
Next good idea. :1st_place_medal: But I like first example more. Currently x, y, w, h has its counterparts of events xChange, yChange, wChange, hChange. The user can easily register listener or provide two way binding and that's fine.
Moving everything to option object would be big change but I don't see big profit.
What do you mean with `ready` event?
`resizableOptions` was planned as a second step of resize feature, but it's good idea to also be a part of GridsterItem options.

**Comment by dipcore** [comment]
Yes, you probably right, I just meant It's rarely case when you need to listen to one of them (x, y, w, h). Most of the time you need to listen to any size/coordinates change what's why my first thought was about having a single "change" event instead of 4.

"ready" triggers then the item is fully rendered. It's useful if you have some complex widgets (i.e charts etc) which should be rendered only after gridster-item component gets placed on the grid and fully rendered.

**Comment by swiety85** [comment]
I see nothing against having additional  `change` event that will be called on every change with info about what change was done. I prefer multiple attribute more because the user is not forced to any specific format of object - he can connect what ever property he wants (e.g. `width` in place of `w`).
You are right with `ready` event. Normal lifecycle hooks are fired before item is correctly rendered.
I will provide it on next release.

**Comment by swiety85** [comment]
Done in v.0.6.0

**Comment by swiety85** [comment]
Since v.0.6.0 (ready) event will not be needed. It should work with native angular ngAfterViewInit lifecycle hook.
