### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by anji405** [swiety85/angular2gridster#308]
Dear Team,

Could you please let us know on the support for Angular7.
The other teams using angular-gridster2 having Angular7 support.
But we really loved the angular2gridster

**Comment by swiety85** [comment]
Of course the support for Angular 7 will be provided in the following days.

**Comment by mathieuprentout** [comment]
Great. Do you have a release date planned for the new version ?

**Comment by swiety85** [comment]
I have exact date, but release should be done till the end of this week.
