### ISSUE TITLE
Angular 7 support

### ISSUE THREAD

**Issue by hijamoya** [swiety85/angular2gridster#311]
7.0.0 does not fully support angular 7 still get:
npm WARN angular2gridster@7.0.0 requires a peer of @angular/common@^6.0.3 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2gridster@7.0.0 requires a peer of @angular/core@^6.0.3 || ^6.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by swiety85** [comment]
Thx for the info. Fixed in v7.0.1.
