### ISSUE TITLE
Question about widget resize

### ISSUE THREAD

**Issue by bradyd19** [swiety85/angular2gridster#312]
I apologize if this question has been addressed, but I was not able to find it by looking at the other issues. I am using chrome and I am resizing a widget by dragging the bottom of the widget.  When the widget hits the bottom of the grid, the grid size is increased, but the widget does not stay at my cursor but starts going back up the screen.  Is this the expected result?  It does not seem to have the same problem in IE.  I am using version 6.0.4.

![image](https://user-images.githubusercontent.com/45105139/48636851-a86c4e00-e991-11e8-91fb-a4c20e018bb0.png)

**Comment by bradyd19** [comment]
Disregard my question, I was able to solve the issue by passing my own class as the element for scrolling and then using the updateGridsterElementData().  My resizing of widget height will now continue without any interruption.

            const elems = document.getElementsByClassName(this.containerClass)[0];
            if (elems) {
                this.subscription.add(
                    fromEvent(elems, 'scroll', { passive: true }).subscribe(() => 
                    this.gridster.updateGridsterElementData()
                    )   
                );
            }

**Comment by swiety85** [comment]
Fixed in v7.0.2
