### ISSUE TITLE
How to represent an empty cell in the backing array?

### ISSUE THREAD

**Issue by danielmekonnen** [swiety85/angular2gridster#314]
Hi, wanted to understand how one can represent an empty cell in the backing array?
I have a 2 lane grid and  2 1x1 items siting in neghbouring rows(left aligned). 
And these two items are represented with models in the backing store.
How can one represent the empty cells on the right?

Thanks in advance, Daniel

**Comment by swiety85** [comment]
Hi, why do you need representation of an empty cell in the array? I'm not sure if I understand you right...
Each item has coordinates `x` and `y`. If there is no item that occupies the cell, it stays empty.

**Comment by danielmekonnen** [comment]
I have widgets coming from DB and I wanted to depend on the sequence as they come from backend: and preferred to store only the width and height of the widgets in db. Empty cell in Gridster is represented by an entity (EmptyItem) in store. 

Say in 2 lane grid, I have 1x1 empty cell, 1x1 Widget Item, 1x2 Widget Item, 1x1 Widget Item,  and 1x1 empty cell.

And this is represented in back store as:

[_EmptyItem(1x1)],WidgetItem(1x1), WidgetItem(1x2), WidgetItem(1x1), EmptyItem(1x1)_]

The question here is now, how would one tell gridster that an EmptyItem in the incoming list is an Empty Cell?

![image](https://user-images.githubusercontent.com/17515820/49674113-12e44b80-fa71-11e8-8234-b1e6d71f2f1c.png)

**Comment by danielmekonnen** [comment]
Any thoughts on this Damien?  Regards, Daniel

**Comment by swiety85** [comment]
I got your point now. Gridster has no solution out of the box. I have some idea how to solve this problem by a trick:
First of all, you need to set `floating: false` in Gridster options.
Just render all items (also empty). On init Gridster will add coordinates (x,y etc.). When Gridster is initialized just remove empty cells from the rendered list - you can use Gridster `(ready)` event to filter out empty cells.
The last point is to build the function that will convert items with coords to a sequence of items and empty cells before saving to the server.

**Comment by danielmekonnen** [comment]
Many many thanks Damian!
