### ISSUE TITLE
Resize grid item width and height relative to item content 

### ISSUE THREAD

**Issue by C-odes** [swiety85/angular2gridster#318]
Hi
I am having an issue where deending on how I resize the item, the content may exceed the item size and get pushed out:  
![contentexceedingdivexample](https://user-images.githubusercontent.com/42934761/50685983-c6fad700-101b-11e9-942d-a638aaee9cc9.gif)

I have a grid item component that has a component as a content. That component has a chart. when I resize , if I resize horizontally the chart becomes larger, but if I resize vertically the chart remains the same . (so I get a lot of free space underneath .

So my question is how can I make it so that it is only allowed to resize in a way proportionate to the content? Dont I need the size of the content to know what values to put for example? OR read from it and place grid item option h : valueRead where valueRead is the  height of the content or something?

**Comment by vistajess** [comment]
Hello @C-odes , 
  We have same scenario I also have chart inside my grid item component, what I did is to listen on changes of the grid item then run the resize function for your chart. I used `Echarts` for my visual/charts and `ResizeSensor`  for detecting resize changes.

ResizeSensor Link:
http://marcj.github.io/css-element-queries/

I just added the files to `angular.cli.json` to be accessible to the app
![image](https://user-images.githubusercontent.com/12708502/52692949-4e832080-2fa0-11e9-9913-14f429e157d0.png)


Code inside my chart component: 
`private onChartInit(echartInstance, option) {
        echartInstance.setOption(option);
        const gridItem = document.getElementById(this.gridItemContainer);
        this.gadgetService.setElementHeight(`#${this.chartId}`, gridItem.clientHeight - 50);

        echartInstance.on('finished', () => {
            ResizeSensor(gridItem, () => {
                echartInstance.resize();
            });
        });
    }`

![resize sensor](https://user-images.githubusercontent.com/12708502/52693213-0b757d00-2fa1-11e9-8868-4a8eb2896b61.gif)

**Comment by C-odes** [comment]
@vistajess  Dude this is gold. Thank you so much!

**Comment by vistajess** [comment]
You're welcome :)
