### ISSUE TITLE
Multiple Components in different gridster items 

### ISSUE THREAD

**Issue by parijatsharma93** [swiety85/angular2gridster#319]
I want to have multiple components rendered inside the gridster.I dont want to create multiple gridster items though,Inside gridster since there is an ngFor can we render multiple components in multiple gridster  items,Dynamic component loader is not required as i will have 5 components and have 5 gridster items. @swiety85 `<gridster [options]="options">
    <gridster-item [item]="item" *ngFor="let item of dashboard">
      <div class="gridster-item-content">
        <br><div class="button-holder">
          <button mat-mini-fab (mousedown)="removeItem($event, item)"
                  (touchstart)="removeItem($event, item)">Remove
            
          </button>
        </div>
        <widget-1></widget-1>
     </div> 
    </gridster-item>
   
</gridster>`

Suppose now i have multiple widgets then what to do ?

**Comment by swiety85** [comment]
I'm sure if I got you right, but if you don't want to render component inside item dynamically you can just render 5 widget components inside each and have ngIf on each - as the simplest solution.
