### ISSUE TITLE
Is there a way to place drag and drop event on some  icon inside widget rather than on whole widget itself

### ISSUE THREAD

**Issue by ashu07** [swiety85/angular2gridster#324]
I want help to figure out a way to put an icon inside the widget which will be responsible for the drag and drop. 
For now, drag and drop works on the whole widget (click and drag).

Any way to get this done ?

**Comment by C-odes** [comment]
YEs. Right now its on the headers.  IF you look at your component you will notice this piece of code: 
gridsterDraggableOptions: IGridsterDraggableOptions = {
    handlerClass: 'panel-heading'
};
The part of your widget that had the css class 'panel-heading' is what is needed to be clicked to drag the widget. 
now ofcourse you can change 'panel-heading" to any other css class name. But put the class name you want there, then let the icon  use that class in your html . 

An example can be  the following:
ts file(component implementing gridster):
gridsterDraggableOptions: IGridsterDraggableOptions = {
    handlerClass: 'dragByButton'
};
HTML:
<button class="dragByButton">click me to drag this widget!</button>

CSS:
dragByButton{
//doesnt really matter what is inside the class
 background-color: white;
}
or    an example for the panel heading class in HTML :
        <div class="panel-heading">
          <h5 class="panel-title">{{ widget.title }}</h5>
        </div>


Hope this helps!

**Comment by ashu07** [comment]
@C-odes Thanks. that works!
