### ISSUE TITLE
Force the column vertical alignment

### ISSUE THREAD

**Issue by josedurand** [swiety85/angular2gridster#325]
Hi, 
To put it simply, I try to constraint all drag n drop behavior only on columns and vertical pushing without swapping (see the gif bellow for demo)

![dragndrop](https://user-images.githubusercontent.com/2630691/52414348-56484e00-2ae4-11e9-8c27-b5bc8092d0bf.gif)

Can i deal with the library settings to reproduce the same behavior ? which parameters must be applied ?

Thanks a lot in advance!

**Comment by swiety85** [comment]
Currently, it's not possible. There is already an issue for that: #105. I can't say when this option will be provided.
