### ISSUE TITLE
Issue while updating coordinates of all widgets

### ISSUE THREAD

**Issue by gauravoodles** [swiety85/angular2gridster#328]
Hi, @swiety85 I have to update co-ordinates of all the widgets like if I resize the first widget, then x and y of other widgets should change. For this I'm using (change), but It's not working for me as it will run the every time according to number of widget. Is there any callback function provided by angular2Gridster which comes in action only when all the coordinates have been updated. My requirement is to save widget 
co-ordinates, so that next time when I land on the page, widgets should render in same order.

**Comment by JusuVh** [comment]
I have the same issue. x/y coordinates do not seem to update in the change events with regards to two-way binding.

**Comment by JusuVh** [comment]
I solved my issues. It was mainly due to responsive behaviour. I had forgotten to map them all with two-way binding.
Great module ! Thx

**Comment by swiety85** [comment]
Have a look at Warning section in https://github.com/swiety85/angular2gridster#example-usage.
This should be the source of your problem.
