### ISSUE TITLE
Importing GridListItem

### ISSUE THREAD

**Issue by bencody** [swiety85/angular2gridster#329]
I'm currently migrating an Angular 5 project to Angular 7 and in doing so I'm also upgrading an Angular2Gridster dependency from version ^1.3.4 to ^7.0.2. I still have a problem importing GridListItem.

I have a ngx-gridster-item with a change callback function:

Template:
```
<ngx-gridster-item (change)="onCellChange($event)">
 ...
</ngx-gridster-item>
```
Component:
```
public onCellChange(event: GridListItem): void {
  // ...
}
```

How do I import GridListItem? It's not contained in `angular2gridster`, and trying to import it from `angular2gridster/lib/gridList/GridListItem` also fails. In version ^1.3.4, I was able to import it from `angular2gridster/dist/gridList/GridListItem`, but that also no longer works.

I noticed this project's home page (https://github.com/swiety85/angular2gridster) mentioned compilation problems and just copying files out from `/projects/angular2gridster/src/lib` into ones own project. I suppose that works for me as a workaround, but will there be a proper solution for this soon?

**Comment by swiety85** [comment]
Should work in v8.0.1
