### ISSUE TITLE
ResponsiveOptions work on browser window size. How to change these property when parent div width changes?

### ISSUE THREAD

**Issue by ashu07** [swiety85/angular2gridster#330]
I am facing an issue when the parent div width changes. the ngx-gridster doesn't detect that.

Ideal case: It should detect and apply the responsive breakpoint.
But currently, breakpoint work on window size.

Any idea of how to handle this when the parent div change. and use xMd, xLg etc in that case

Any help is appreciated

**Comment by C-odes** [comment]
Hey.
What do you mean? When the div of a component changes ? Or the gridster itself?

**Comment by ashu07** [comment]
So, I have side nav in the application, when the sidnav is opened, the container width is reduced, but In that case how the widget position would be made responsive so that the last one comes to the next row.

To fix this, I have changed the lanes to 2 and reload the gridster component on the opening of sidenav and lanes to 3 when sidenav is closed

But in this course, the x and y value are changed and it doesn't render as same when i close the Sidenav.
I just want to make it responsive but want to retain the values as before


Any suggestions?

**Comment by C-odes** [comment]
Sorry but please take screenshots or even better make a gif using a free program called s reenToGif.
Would help a lot.
Download it here
https://www.screentogif.com

**Comment by OBorce** [comment]
I think ashu07 means something like this:
https://codesandbox.io/s/lyyyojl5k9?fontsize=14

when you toggle the sidebar the grid expands but no change or reflow is done to the items, and items can't be moved to the expanded grid.

**Comment by ashu07** [comment]
@OBorce correct, When I am doing reflow also it takes the same config as the browser screen size is still the same and renders the 3 widgets.
To solve this, I am giving new options value to convert into 2 grid. which might work but on doing that It is calling API calls as the grid position are changed but ideally it should be same.


What I feel should be is that the breakpoint should be on the parent Div of gridster rather than the browser width.

Please Let us know your thoughts on this.

**Comment by swiety85** [comment]
Duplicate #201
