### ISSUE TITLE
How can I use this library with systemjs?

### ISSUE THREAD

**Issue by PavelAlexandra** [swiety85/angular2gridster#34]

**Comment by swiety85** [comment]
Thanx for asking. I forgot to provide installation steps for System.js. I've just provide it in wiki,
 you can [read it here](https://github.com/swiety85/angular2gridster/wiki/Getting-started#additional-steps-for-systemjs).
Please give me a hint if it works for you.

**Comment by PavelAlexandra** [comment]
Thanks for the quick update. I eventually figured it out, but it's good to be there for others that might need as well.
