### ISSUE TITLE
Angular2gridster freezes when we increase size of first widget or sometimes drag it 

### ISSUE THREAD

**Issue by brainyaashish** [swiety85/angular2gridster#347]
Angular2gridster freezes when we increase size of first widget or sometimes drag it .

this error can be seen  in the console of the Demo project (reproduce) .
https://swiety85.github.io/angular2gridster/
this error is started recently was not happening earlier .

ERROR TypeError: Cannot set property '0' of undefined

![image](https://user-images.githubusercontent.com/33567273/67162755-e08bc600-f384-11e9-8af4-2737edcc2082.png)

**Comment by andre-gois** [comment]
Same problem here, started after updating from 8.1.0 to 8.1.1
