### ISSUE TITLE
Getting issue Unable to get property 'toString' of undefined or null reference in IE11 (Angular 8)

### ISSUE THREAD

**Issue by sivaecekrr** [swiety85/angular2gridster#348]
Getting below issue in IE 11 with Angular 8 setup. Please help me with the issue. Thanks.

"angular2gridster": "^8.1.2"

ERROR TypeError: Unable to get property 'toString' of undefined or null reference

**Comment by swiety85** [comment]
Sorry to say but I don't have access to IE11 currently. I could try to understand the problem and fix it blindly but I would need detailed error info with stack trace.

**Comment by sivaecekrr** [comment]
@swiety85 issue is due to someother component and widgets are not displayed due to style issue. After removing https://github.com/swiety85/angular2gridster/blob/master/src/app/app.component.css#L49. But the same works with demo site https://swiety85.github.io/angular2gridster/. Will close this since issue is not related.
