### ISSUE TITLE
Calculate Cell Size

### ISSUE THREAD

**Issue by JIJL** [swiety85/angular2gridster#35]
There are some defects in calculateCellSize method of GridsterService。
When we calculate container height and width，we need to minus the padding。
This is my some advice, hope to adopt。

**Comment by swiety85** [comment]
Thanx  for info, but I'm not sure I understand you problem right.
What container do you mean? Gridster or GridsterItem?
Please provide more comprehensive informations, that I can react and solve it fast.

**Comment by JIJL** [comment]
The container i said is Gridster.I can't reproduce the problem now.

At that time, I use 4 tag of Gridster in my AppCompnent.And output the gridster size change event to help other gridster change size.Gridster appear  the calculation error at this time.Because of the error, div element appeared the scroll bar.In debug mode, I found Gridster no minus padding.So I have modified the source code, then the problem solved.

Finally, I hope Gridster  support in a Component using multiple Gridster .Because now GridsterItem in drag mode, position calculation is not correct.And under the condition of multiple Gridster, only the first can change the size when browser window size changes

**Comment by swiety85** [comment]
Does the problem appears only in case of multiple Gridster components in one view? Does all these Gridsters where connected to the same "items" list?
If you solved the problem by modifying source code I would appreciate if you send me it, that I can better and faster understand and fix the problem.
There is a task to support multi Gridsters in more comprehensive way ( #28 ) but it's planned on 0.7 release. The multiple Gridster case was not tested so far, but I will have a better focus on it as soon as possible. 
Thank you for all your input and I look forward to get more info from you.

**Comment by JIJL** [comment]
I sent an email to your Gmail.You can see details there

**Comment by swiety85** [comment]
This problem could be solved by one of following issues: #21, #27, #28. Because I got not enough explanations, I have no other choice then close this issue.
