### ISSUE TITLE
How to set the height relative to the gridster height  ?

### ISSUE THREAD

**Issue by brainyaashish** [swiety85/angular2gridster#354]
@swiety85 please help urgent 
How to set the height relative to the gridster height  ?

![image](https://user-images.githubusercontent.com/33567273/68793428-39443b00-0673-11ea-9a0f-765f028747ee.png)

**Comment by swiety85** [comment]
Hi, I'm not sure if I understand a question. Please provide a better description of your problem and I will try my best to help you.

**Comment by brainyaashish** [comment]
@swiety85  the height of the widget is  not  able to vary according the content in the gridster .

in the image above the YEllow color shows the height of the child (content ) is not getting streched as per the parent (gridster)

**Comment by brainyaashish** [comment]
@swiety85  : I have some urgent requirement to vary height relative to item content.
your help is very much appreciated .

**Comment by brainyaashish** [comment]
@swiety85  Please help me with this issue

**Comment by swiety85** [comment]
Is your use case is to have only one row of widgets that should always fit the container height?

**Comment by brainyaashish** [comment]
yes , but user can increase the height of the gridster and i get the white space ,  how to make autoheight . the class ="gridster-item-inner" element  , if i search it and apply the height dynamically it sets for other widgets too .

**Comment by swiety85** [comment]
If you have a Gridster option `direction: 'vertical'` the height of the items is calculated dynamically by:
* widget width (px),
* `h` - item size (cell amounts),
* `widthHeightRatio` - proportion between the width and the height (default = 1).

My suggestion is to change the `widthHeightRatio` on gridster height change.
x - gridster width
y - gridster heigth
l - number of lanes
```
ratio = x / l / y
```
This should change all widgets height to occupy always the full gridster space in height.
The `widthHeightRatio` can be applied as follows:
`gridster.setOption('widthHeightRatio', ratio).reload()`.
