### ISSUE TITLE
drag and drop not working if widget array is empty

### ISSUE THREAD

**Issue by prasad1791** [swiety85/angular2gridster#356]
Hi , 
if i am keeping widget array empty initially then drag and drop functionality not working 
For Eg.
`public widgets: Array<any> = [];`    //not working
`public widgets: Array<any> = [{}];`   //working but not useful

  why ?

**Comment by swiety85** [comment]
What is exactly not working? What you expect in what case and what happened?

**Comment by prasad1791** [comment]
it's working , i don't know why it didn't worked earlier , but thanks !!. I am closing this issue
