### ISSUE TITLE
Support for angular 9

### ISSUE THREAD

**Issue by Zwergenpunk** [swiety85/angular2gridster#361]
Can you add support for angular 9?

with angular 8 we always see the warning:
`npm WARN angular2gridster@8.1.2 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN angular2gridster@8.1.2 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.`

**Comment by swiety85** [comment]
Please use v9.0.0
