### ISSUE TITLE
Display grid lines

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#37]
Would be cool if the user can configure to show grid lines when dragging items or permanently.

**Comment by dhamecha** [comment]
Any update on this feature?

**Comment by swiety85** [comment]
Hi, it is planned with lower priority, but since there are questions about this feature, I will try to deliver this somewhere in December.
Hope it's fine for you.

**Comment by dhamecha** [comment]
Thank you for the update!

**Comment by dhamecha** [comment]
Hi @swiety85 any updates on this? Please let me know. Thanks a ton.

**Comment by swiety85** [comment]
Hi, the plan hasn't changed. We will try to deliver this feature till the end of December.

**Comment by IAMtheIAM** [comment]
Great, I also look forward to this feature.

**Comment by rudzikdawid** [comment]
https://github.com/swiety85/angular2gridster/commit/38a5ca4a400639c253affa120bf445b0afd7ef45 already available on master

**Comment by dhamecha** [comment]
Thank you for the feature.
