### ISSUE TITLE
D&d ngOnInit gridster-item bug

### ISSUE THREAD

**Issue by pjbogacz** [swiety85/angular2gridster#38]
### How to reproduce:
- (in vertical, draggable) remove all elements in the first column
- drag a **new** element to any col>1 (0's position)
- alt: drag a **new** element to any col that has some free slots to the left 

### What happens:
- newly added element is teleported to 0x0 position (or any first free slot served by findDefaultPosition() func)
- position cords are not updated

<a href="https://ibb.co/iWZoMQ"><img src="https://preview.ibb.co/cauoMQ/Zrzut_ekranu_z_2017_05_06_14_56_43.png" alt="Zrzut_ekranu_z_2017_05_06_14_56_43" border="0"></a>

### Suggested solution
Remove or revalidate findDefaultPostion() in ngOnInit in gridster-item.component - the position is checked prior i.e. in gridList:findPositionForItem and collitions taken care as well. When moving item component that already exists you do not call the function findDefaultPosition and that works fine.

**Comment by swiety85** [comment]
Thanks for info. I've noticed this issue already. Fix is already available in #44. I would be glad if you can check it before I will merge it.

**Comment by swiety85** [comment]
Bug fix is already available under v. 0.5.3.
