### ISSUE TITLE
Position cords not populated corectly

### ISSUE THREAD

**Issue by pjbogacz** [swiety85/angular2gridster#39]
### How to reproduce:
- play around with d&d **new** elements to the grid (it's relatively easy when the pointer cannot find focus & does not visualize the position - but the bug occurs randomly on many other occasions)

### What happens: 
- position cords are invalid (not related with issue #38)

<a href="https://ibb.co/dCfsFk"><img src="https://preview.ibb.co/nCnHgQ/Zrzut_ekranu_z_2017_05_06_15_50_59.png" alt="Zrzut_ekranu_z_2017_05_06_15_50_59" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>image hosting for ebay</a><br />

**Comment by pjbogacz** [comment]
to make it worse, all 3 positions from - gridListItem (GridsterItemComponent), elements stored in local array (i.e. widgets) and html gridster-items - can be out of sync at the same time

**Comment by swiety85** [comment]
I have theory that the source of bug is the same as in #38. The fix for that issue already available. Please check if it solves also this one.

**Comment by swiety85** [comment]
Bug fix is already available under v. 0.5.3.
