### ISSUE TITLE
IGridsterOptions was not found

### ISSUE THREAD

**Issue by Maccodonaldo** [swiety85/angular2gridster#4]
Do you know why I get this error ? 

```
WARNING in ./src/app/core/gridster/gridster.component.ts
29:91 export 'IGridsterOptions' was not found in './gridster.service'
```

**Comment by michalstepien** [comment]
Hi, do you use actual repo?

**Comment by Maccodonaldo** [comment]
Hi :) 
I created a new project and wanted to "play" with your gridster code. I used the gridster src folder and the index.ts file, which allowed me to add it to my  ngModule. Just like you did in your demo folder.

**Comment by swiety85** [comment]
I think it's related with https://github.com/webpack/webpack/issues/2977.
This problem will be fixed soon.

**Comment by Maccodonaldo** [comment]
works finde now !! :smile:
