### ISSUE TITLE
Gridster options: dragAndDrop is breaking the app

### ISSUE THREAD

**Issue by GabrielGamy** [swiety85/angular2gridster#41]
I set the dragAndDrop option to false, and when I navigate to a new page my app breaks.

  gridsterOptions:IGridsterOptions = { 
    lanes: 5,  
    direction: "vertical", 
    dragAndDrop: false 
  }

I found this into the gridster-item.component.ts class:

this.dragSubscription is undefined but into the ngOnDestroy(), you try to unsubscribe on it

    ngOnInit() {
        this.gridster.registerItem(this);

        if(this.gridster.options.dragAndDrop) {
            this.createMouseDrag(this.$element);
            this.createTouchDrag(this.$element);

            // Update position
            this.dragSubscription = this.dragging.subscribe((pos) => {
                if(!this.pin){
                    this.$element.style.top = (pos.top - this.gridster.$element.offsetTop) + 'px';
                    this.$element.style.left = (pos.left - this.gridster.$element.offsetLeft) + 'px';
                }           
            });
        }
    }
    ngOnDestroy() {
        let index = this.gridster.items.findIndex((z) => z == this);
        if(index){
            this.gridster.items.splice(index,1);
        }
        this.dragSubscription.unsubscribe();
    }

**Comment by swiety85** [comment]
I don't know which version of angular2gridster you use but the code of [`gridster-item.component.ts`](https://github.com/swiety85/angular2gridster/blob/0.5.2/src/gridster-item/gridster-item.component.ts) is different than code that you place in your comment.
Despite of this I've tied to reproduce this issue as you described but everything seams to work.
Please update your project to angular2gridster v. 0.5.2 and check again.

**Comment by GabrielGamy** [comment]
Thanks
