### ISSUE TITLE
widthHeightRatio option not updating

### ISSUE THREAD

**Issue by czebe** [swiety85/angular2gridster#42]
Using this.gridster.setOption('widthHeightRatio', aspect).reload(); will not update the aspect ratio, it stays at the initial setting.

GridsterComponent.prototype.setOption() function is missing the implementation for the widthHeight option.

**Comment by swiety85** [comment]
This was not implemented yet. I've done it (#45). I will soon create new release with this update.

**Comment by swiety85** [comment]
Missing functionality is already available under v. 0.5.3.

**Comment by czebe** [comment]
Thank you, much appreciated!
