### ISSUE TITLE
Gridster Height

### ISSUE THREAD

**Issue by speculees** [swiety85/angular2gridster#48]
Gridster height is not getting minimum height that should match the sum of item heights.

**Comment by swiety85** [comment]
What items orientation (direction) are you using, vertical or horizontal?
I would appreciate some more input about the problem you have.

**Comment by speculees** [comment]
No problem. Here is my config:

`export const GridsterOptions: IGridsterOptions = {
  lanes: 3,
  direction: 'vertical',
  dragAndDrop: true,
  resizable: true,
  maxWidth: 3,
  maxHeight: 2,
  widthHeightRatio: 1
};`

![screencapture-localhost-4200-main-dashboard-1495546298545](https://cloud.githubusercontent.com/assets/3776493/26356710/358940ce-3fcd-11e7-8607-b6e33c829e90.png)

Topics widget colored in light gray is above grid colored a bit darker. As you can see there is some unnecessary space i grid. I see no function in source that calculates this space.

**Comment by swiety85** [comment]
The space under is reserved in case when you have more then one item and you would like to move one under another. The empty space under has the same height as the highest element on the board.
Is it a big problem for you?
I'm considering to create a task to dynamically adopt gridster height only in moment of dragging. By default it would have height only to fit available items. What do you think?

**Comment by speculees** [comment]
That sounds awesome. Exactly what I was thinking. I need this because I'm planing to have multiple gridsters across  md-tab's. While on the subject I have another issue concerning the gridster within md-tab.
I shall post this in another thread.

**Comment by aarthidhina** [comment]
This is exactly what i want, when this will be available

**Comment by swiety85** [comment]
The plan is to provide this functionality by June 30, 2017.. more then less. :)

**Comment by swiety85** [comment]
Use `shrink=true` option in GridsterComponent in v.0.6.0
