### ISSUE TITLE
Gridster within md-tabs

### ISSUE THREAD

**Issue by speculees** [swiety85/angular2gridster#49]
Hi again. I have the following code here:

`<md-tab-group [dynamicHeight]="true" [selectedIndex]="selectedDashboard" (selectChange)="onTabChange($event)" [dynamicHeight]="true">
      <md-tab *ngFor="let dashboard of dashboards; let i = index;" >

        <ng-template md-tab-label>
          {{dashboard.title}}
        </ng-template>

              <gridster [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions" #gridster>
                <gridster-item [(x)]="widget.x" [(y)]="widget.y" [(w)]="widget.w" [(h)]="widget.h" *ngFor="let widget of dashboards[selectedDashboard].widgets">
                  

                  <md-toolbar class="panel-heading" color="">
                    {{widget.title}}
                  </md-toolbar>

                  <verso-notification class="panel-body" *ngIf="widget.type == 'notification'"></verso-notification>
                  <verso-target class="panel-body" *ngIf="widget.type == 'target'"></verso-target>
                  <verso-topic class="panel-body" *ngIf="widget.type == 'topic'"></verso-topic>
                  <verso-note class="panel-body" *ngIf="widget.type == 'note'"></verso-note>
                  <verso-task class="panel-body" *ngIf="widget.type == 'task'"></verso-task>
                  <verso-kpi class="panel-body" *ngIf="widget.type == 'kpi'"></verso-kpi>

                </gridster-item>
              </gridster>
  

      </md-tab>
    </md-tab-group>`

There is a strange offset between the mouse and gridster-item when I put gridster in md-tab. 
![imageedit_6_8950083445](https://cloud.githubusercontent.com/assets/3776493/26358803/0a06dc84-3fd4-11e7-84a7-4612d2314247.gif)

**Comment by swiety85** [comment]
Thanx for info. I will have a look on this soon.

**Comment by speculees** [comment]
okay, here is my workaround. The tab content is placed outside of md-tab. 

  <md-tab-group [dynamicHeight]="true" [selectedIndex]="selectedDashboard" (selectChange)="onTabChange($event)" [dynamicHeight]="true">
    <md-tab *ngFor="let dashboard of dashboards">

      <ng-template md-tab-label>
        {{dashboard.title}}
      </ng-template>

    </md-tab>
  </md-tab-group>

  <section *ngFor="let dashboard of dashboards; let i = index;">
    <div *ngIf="selectedDashboard === i">
      <gridster [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions" #gridster style="height: 1200px">
        <gridster-item [(x)]="widget.x" [(y)]="widget.y" [(w)]="widget.w" [(h)]="widget.h" *ngFor="let widget of dashboards[selectedDashboard].widgets">
          

          <md-toolbar class="panel-heading" color="">
            {{widget.title}}
          </md-toolbar>

          <verso-notification class="panel-body" *ngIf="widget.type == 'notification'"></verso-notification>
          <verso-target class="panel-body" *ngIf="widget.type == 'target'"></verso-target>
          <verso-topic class="panel-body" *ngIf="widget.type == 'topic'"></verso-topic>
          <verso-note class="panel-body" *ngIf="widget.type == 'note'"></verso-note>
          <verso-task class="panel-body" *ngIf="widget.type == 'task'"></verso-task>
          <verso-kpi class="panel-body" *ngIf="widget.type == 'kpi'"></verso-kpi>

        </gridster-item>
      </gridster>
    </div>
  </section>

**Comment by speculees** [comment]
Try this...

In gridster-item.component : 

`const dragStartSub = draggable.dragStart.subscribe((event: DraggableEvent) => {
  this.zone.run(() => {
     this.gridster.onStart(this.item);
     this.isDragging = true;
     cursorToElementPosition = event.getRelativeCoordinates(this.$element, event);
  });
});

const dragSub = draggable.dragMove.subscribe((event: DraggableEvent) => {
   this.$element.style.top = (event.clientY - cursorToElementPosition.y) + 'px';
   this.$element.style.left = (event.clientX - cursorToElementPosition.x) + 'px';
   this.gridster.onDrag(this.item);
});`

And in DraggableEvent.ts replace :

'getRelativeCoordinates(container: HTMLElement, event: DraggableEvent): { x: number, y: number } {
   let style = window.getComputedStyle(container, null);
   return {
       x: event.clientX - parseInt(style.getPropertyValue("left"), 10),
       y: event.clientY - parseInt(style.getPropertyValue("top"), 10)
    };
}`

**Comment by speculees** [comment]
Now on resize...

in DashboaordComponent:

    @HostListener('window:resize', ['$event'])
    onResize(event) {
        this.gridster.reload(); // Cannot read property 'reload' of undefined
    }

**Comment by swiety85** [comment]
Thanks for hint I will have a closer look on this.

**Comment by swiety85** [comment]
Problem should be fixed in v.0.6.5. Please check it.
P.S. Gridster must be reloaded on every tab change to render it correctly in every tab e.g. `(selectChange)="gridsterComponent.reload()"`.
Please give me a hint if it works for you.

**Comment by speculees** [comment]
Solved
