### ISSUE TITLE
zone.js violations

### ISSUE THREAD

**Issue by ronnyek** [swiety85/angular2gridster#50]
So I've started seeng zone.js complaining about performance problems: 
`[Violation] 'load' handler took 517ms
45zone.js:1157 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.
zone.js:472 [Violation] 'load' handler took 504ms
[Violation] Forced reflow while executing JavaScript took 184ms
zone.js:1157 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive.
zone.js:1489 [Violation] 'setTimeout' handler took 50ms
zone.js:472 [Violation] 'message' handler took 319ms`

I think there are just options that we can pass in draggable.ts, for the passive: true. Seeing as I'm no expert in this area, does this seem feasible while keeping backwards compatibility?

**Comment by swiety85** [comment]
I will have a look on that. Thanx for info!

**Comment by ronnyek** [comment]
Honestly I think this is new error/performance stuff in chrome/zone.js  and have seen warnings in lots of different libraries and stuff... Maybe not caused by your library

**Comment by swiety85** [comment]
It seams that warnings in Vorbose mode are not problematic in case of angular2gridster. Despite of that I will have an eye on these warnings in further implementations.
