### ISSUE TITLE
Please add the dynamic layout scene when dragging and dropping

### ISSUE THREAD

**Issue by sunjiongjun** [swiety85/angular2gridster#53]
In gridster-item.component.ts file 

we should update dragMove subscribe function  

const dragSub = draggable.dragMove
                .subscribe((event: DraggableEvent) => {
                    this.gridster.gridsterRect = this.gridster.$element.getBoundingClientRect(); //add this code fix
                    let left = this.gridster.gridsterRect.left < 0 ? 0 : this.gridster.gridsterRect.left;
                    let top = this.gridster.gridsterRect.top < 0 ? 0 : this.gridster.gridsterRect.top;

                    this.$element.style.top = (event.clientY - cursorToElementPosition.y -
                        top) + 'px';
                    this.$element.style.left = (event.clientX - cursorToElementPosition.x -
                        left) + 'px';

                    this.gridster.onDrag(this.item);
                });

**Comment by swiety85** [comment]
Thank you for bug solution, but could you describe what is wrong that this change is required?
With this I am able to investigate whether the bug is fixed or not.

**Comment by ceejeeb** [comment]
I also would like a fix for this. 
The reason: the method updateGridsterElementData() is only ever called in ngAfterViewInit and when the document is scrolled. If the page loads content into the dom above the gridster that changes the position of the gridster component the dragging position is off. Therefor it would be better to refresh the gridsterRect before the dragging starts. Or expose the updateGridsterElementData method so we can call it when we choose.

**Comment by swiety85** [comment]
Now it's clear. You are right. I will fix it as soon as possible. Thanx!

**Comment by swiety85** [comment]
Updating gridster element position is implemented. Also updateGridsterElementData is now public and free to use from outside for any other occasion. Fix available in v.0.6.5.
Please check and give me a hint if it works for you.
