### ISSUE TITLE
Suspend Auto Layout

### ISSUE THREAD

**Issue by ceejeeb** [swiety85/angular2gridster#58]
Is there a way to have a layout (vertical, horizontal) that doesn't compact in any direction so tiles can float. Or can we have the ability to turn off the 'auto compacting' whilst we manipulate the tiles in code.

See the example:
http://plnkr.co/edit/nP2uqGMy4bT6zG7GiEAI?p=preview
I am simply replacing a tile with one with identical x and y properties but the resulting dashboard layout differs.
When I replace an item in the list of 'tiles' the layout shifts down to fill the gap left my the removed tile. Then it adds the new tile to the grid and that pushes the one in its place to the left.

Hopefully that makes sense.

**Comment by swiety85** [comment]
Good point - I haven't checked that use case. Unfortunately so far there is no option to switch off compacting (but I try to provide this soon - #59).
Despite of that replacing item should work as expected - this is a bug and the good news is that it's trivial to fix. The fix will be provided with closest major version 0.6.0 that will be released in one of next days.
Thanx for info.

**Comment by swiety85** [comment]
Please check if you have still this problem on v.0.6.0
