### ISSUE TITLE
Option to switch off compating/pulling items

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#59]
Provide a way to have a layout (vertical, horizontal) that doesn't compact in any direction so tiles can float.
This could be configured by Gridster option: `direction="none"`.

**Comment by rodrianderson** [comment]
Some position for this issue? At this version, has some alternative for this issue?

**Comment by menme95** [comment]
I've just want to know if it is driection or direction

**Comment by swiety85** [comment]
`direction="none"`
Sorry, it was a typo. I've checked and it seams that switching pulling should not be a big effort and I will try to provide it in nearest release.

**Comment by SlapBassist** [comment]
Any progress on this? Using this library in an application and this would be a great feature to be able to position items anywhere, save it to a database, and reload the page with the items in the previously dropped positions.

**Comment by swiety85** [comment]
Yesterday I was able to implement it roughly. I will polish the code and test it and I think I will be available till the end of next week.

**Comment by swiety85** [comment]
Done in v.0.6.8. More info in [Wiki](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#gridstercomponent).
