### ISSUE TITLE
Highlight doesn't initialize for draggable prototype if already positioned over the grid

### ISSUE THREAD

**Issue by michaelgira23** [swiety85/angular2gridster#64]
Hello,

I have a menu bar with a fixed position at the bottom of the viewport which contains a bunch of Gridster Item Prototypes. Because the grid stretches the whole height of the viewport, the prototypes are resting within the dimensions of the gridster grid. When the user drags one of the prototypes onto the grid, the highlight does not initially work. You have to drag the prototype either left or right outside the grid's dimensions then drag it back in for the highlight to work.

Is there a way to fix this or manually trigger an `enter` event for the prototype if it starts within the grid? Thanks!

**Comment by swiety85** [comment]
Hi, which version of Angular2gridster are you currently using? I've fixed one similar problem already. This fix is available in v.0.6.0.

**Comment by michaelgira23** [comment]
Ah, I was indeed using v0.5.3 before. After upgrading to v0.6.X, the highlight does work the first time, but doesn't work any other time until you refresh the page.

Also, this may or may not be related, but after upgrading to v0.6.X dragging any new module will not put it in the highlighted position. Instead, it will change the x and y values to the first available space (Ex. drag it towards the middle but places it in the top-leftmost corner). The component is changing the x and y position, as getting rid of the two-way binding keeps the x and y coordinates the prototype was dropped on. I saw there were quite a few changes in v0.6.0 so forgive me if this is a configuration error on my part.

Additionally, resizing a gridster item doesn't seem to work in v0.6.X. When resizing, it seems to make the height and width both 0px.

Despite these issues angular2gridster is a lifesaver and I greatly appreciate your work!

**Comment by swiety85** [comment]
In version 0.6.0 default options were accidentally removed. There is a big chance that this could be the reason of your problem. Try to set explicitly widthHeightRatio (default val should be 1) or better update to v.0.6.1 Yesterday I've made a fix for this.
I'm really glad, that you like it.
In case of any questions or problems, don't hesitate and write.

**Comment by michaelgira23** [comment]
Thanks for the response. After playing around a bit, I was able to fix the problems caused from upgrading to v0.6.0/v0.6.1. You're right, I did have to set the `widthHeightRatio` to `1` in v0.6.0 but that was fixed by upgrading to v0.6.1.

The gridster item resize problem was solved by setting the `maxWidth` and `maxHeight` for all items. I just set them both to `Infinity` like default.

The x/y position change after dragging a prototype onto the grid was fixed by setting `responsiveView` to either `true` or `false`. **You _must_ set `responsiveOptions` to contain breakpoints though, even if you set `responsiveView` to `false`.**

After upgrading to the latest version (0.6.1), you're able to properly drag the first item onto the grid the first time, but not any other time until refreshing the page. You can replicate this by visiting the [demo](https://swiety85.github.io/angular2gridster/) and setting the `.widgetbar` to have the following CSS properties:

```css
.widgetbar {
    position: fixed;
    top: 15rem;
    z-index: 100;
}
```
This should put the widget bar over the grid. If you drag the first item onto the grid, it works as intended. Dragging a second or third item onto the grid will not work and put them grid item on top of the most recently added item. The only way to circumvent this is to drag the item outside the grid bounds, then back in.

**Comment by swiety85** [comment]
Thanks for info. I will fix it as soon as possible.

**Comment by swiety85** [comment]
Should be fixed in v.0.6.2. Please check and give me a hint if it works for you.
Thanx

**Comment by michaelgira23** [comment]
Yes, it works! Thank you very much!
