### ISSUE TITLE
Responsive behavior on real devices not working

### ISSUE THREAD

**Issue by AlMuIssues** [swiety85/angular2gridster#65]
_Test with angular2gridster version: 0.6.0_

I tried out your demo application on PC(Chrome), on android smartphone, iPad and iPhone. I think the application work only on PC as expected . See below:

- iPhone portrait: 2 lanes (as expected )
- iPhone portrait in chrome: 2 lanes (as expected )
- iPhone landscape : 2 lanes (**3 expected** )
- iPhone landscape in chrome: 3 lanes (as expected )
---------------------------------------------------------------------------------
- iPad portrait: 2 lanes (**4 expected** )
- iPad portrait in chrome: 4 lanes (as expected )
- iPad landscape : 2 lanes (**4 expected** )
- iPad landscape in chrome: 4 lanes (as expected )
--------------------------------------------------------------------------------
Is it a bug in new feature responsive behavior? Or I don't understand how to use this feature...

**Comment by swiety85** [comment]
To be honest I tested it only on android and desktop devices.
It seams that it doesn't work only for Safari and I already found some info about common problem with window resize event in Safari.
This is a bug and I will provide a fix as soon as possible.
Thank you for info!

**Comment by swiety85** [comment]
Can you please check if 0.6.1 solves problem with apple devices and give a hint if it works or not.

**Comment by AlMuIssues** [comment]
I've checked your demo with apple devices now and it works fine. Now I'll try 0.6.1 in my project. Thanks for quick fix
