### ISSUE TITLE
GridsterPrototypeService isInsideContainer issues

### ISSUE THREAD

**Issue by HyenaCros** [swiety85/angular2gridster#71]
I noticed a couple issues with how the gridster prototype service handles prototypes entering the container. Currently, the enter event is only fired when the entire prototype is inside the container. This an issue if the prototype is ever taller than the grid. If the grid has a height of  300px and the prototype's height is 301px, the service doesn't know to expand the grid to fit the prototype. 
It is also an issue if the prototype resizes during the onEnter event. As another example, say the prototype is entering near the bottom of the grid and expands such that its bottom is lower than the grid's bottom. The prototype will trigger the onEnter event and resize, but is no longer 100% inside the grid and cannot be added until it is moved further up. This also technically applies to width as well for horizontal grids.
My workaround was to remove the part of the isInsideContainer function comparing the bottoms. This allowed me to add the prototype if it was below but not completely inside the grid, even if its height was greater than the grid's.
I propose adding an option to the grid to determine which side(s) you want to act as an 'entrance' like I have. i.e. if you specify you want 'entrances' at the bottom and left of the grid, the isInsideContainer function will return:
    `(elRect.left > containerRect.left  && elRect.right < containerRect.right && elRect.top > containerRect.top) ||
    (elRect.right < containerRect.right && elRect.top > containerRect.top && elRect.bottom < containerRect.bottom);`

**Comment by swiety85** [comment]
Since v1.0.0-alfa you can configure `tolerance` property that works very similar like [jquery droppable `tolerance` option](http://api.jqueryui.com/droppable/#option-tolerance). By default it uses `pointer` tolerance. More info in [wiki](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#inputs).
Hope that it solves your problem.
I appreciate any response.
