### ISSUE TITLE
Drag & Drop doesn't work in Edge on touch device (tablet / mobile)

### ISSUE THREAD

**Issue by tw2as** [swiety85/angular2gridster#72]
Tested on official demo - https://swiety85.github.io/angular2gridster/

**Comment by swiety85** [comment]
Thanks for info. I will try to fix it as soon as possible.

**Comment by swiety85** [comment]
My favorite browser.. :-P The problem seams to be the same as here: https://github.com/bevacqua/dragula/issues/273.
Solution is to assign css property `touch-action: none;` to the element that is a drag handler.
Please write me back if it works for you.

**Comment by tw2as** [comment]
Yep. That seems to help. Will you integrate it into the core code so this css property is added automatically to the handlerClass?

**Comment by swiety85** [comment]
Yep, I will do it. I will try to provide it in next release.

**Comment by tw2as** [comment]
Great. Thanks.
_touch-action: none_ also helps for "drag me" elements as seen on the Demo

**Comment by swiety85** [comment]
Done in v 0.6.7.
