### ISSUE TITLE
ResponsiveView & responsiveOptions defaults causing snap issues with new items

### ISSUE THREAD

**Issue by HyenaCros** [swiety85/angular2gridster#74]
Say for example I define in the gridster options to have 12 lanes but omit responsiveView and responsiveOptions. While 12 lanes will exist on the grid, any new items added to the grid will not place in their proper position, but instead snap up and left. Once an item is added it behaves normally, but the initial placement is incorrect. If you modify the demo and remove the responsive fields from the gridster options and increase the number of lanes you can see this in action. Manually defining the responsive options to have the same lane is the only way to make things work properly. It took me a couple days to realize this, so I'm sure others would like to know if experiencing the same problem. Also, sorry for finding/posting so many issues XD

**Comment by swiety85** [comment]
You are good tester.  :1st_place_medal: 
No problem, it's not your fault that there is so many bugs to fix. I appreciate bug report or improvement idea every time.
I will take care about this issue. Thanx! :-)

**Comment by swiety85** [comment]
Should be fixed in v.0.6.5. Please have a look a write if it works for you.
