### ISSUE TITLE
Can someone help me how to implement resize?

### ISSUE THREAD

**Issue by vistajess** [swiety85/angular2gridster#75]
I just followed the documentation and the code of the demo as well.
But it seems to be the resize doesnt functioning. I dont know what I did wrong and I need help pls.

Here's my code for my component: 
 `import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-gridster-component',
  templateUrl: './gridster-component.component.html',
  styleUrls: ['./gridster-component.component.css']
})
export class GridsterComponentComponent implements OnInit {

  widgets: Array<any> = [];
  gridsterOptions = {
    lanes: 6, // how many lines (grid cells) dashboard has
    direction: 'vertical', // items floating direction: vertical/horizontal
    dragAndDrop: true, // possible to change items position by drag n drop
    resizable: true // possible to resize items by drag n drop by item edge/corner
  };

  constructor() { }

  ngOnInit() {
  }

  addWidget(): void {
    this.widgets.push({
        x: 4, y: 0, w: 1, h: 1,
        dragAndDrop: true,
        resizable: true,
        title: 'Basic form in3puts 5',
        content: `Loremp ipsum`
    });
    console.log('widget push', this.widgets);
  }

}`

And here's for the template:

`<section>
  <div>
    <button (click)="addWidget()">Add Widget</button>
  </div>
  <gridster [options]="gridsterOptions" [draggableOptions]="gridsterDraggableOptions" (optionsChange)="optionsChange($event)" #gridster1 style="min-height: 500px;">

    <gridster-item *ngFor="let widget of widgets; let indx = index" #itemComp [options]="itemOptions" [dragAndDrop]="widget.dragAndDrop" [resizable]="widget.resizable" [(x)]="widget.x" [(y)]="widget.y" [(xSm)]="widget.xSm" [(ySm)]="widget.ySm" [(xMd)]="widget.xMd"
      [(yMd)]="widget.yMd" [(xLg)]="widget.xLg" [(yLg)]="widget.yLg" [(xXl)]="widget.xXl" [(yXl)]="widget.yXl" [(w)]="widget.w" [(h)]="widget.h" (change)="itemChange($event, gridster1)" style="border: 1px solid red;">

      <div class="panel-heading">
        <h5 class="panel-title">{{ widget.title }}</h5>
      </div>

      <div class="panel-body">
        <p>
          <label>
                        <input type="checkbox" [(ngModel)]="widget.dragAndDrop" value="true"> Draggable
                    </label>
          <label>
                        <input type="checkbox" [(ngModel)]="widget.resizable" value="true"> Resizable
                    </label>
          <button (click)="setWidth(widget, widget.w+1, $event, gridster1)">width +</button>
          <button (click)="setWidth(widget, widget.w-1, $event, gridster1)">width -</button>
          <button (click)="setHeight(widget, widget.h+1, $event, gridster1)">height +</button>
          <button (click)="setHeight(widget, widget.h-1, $event, gridster1)">height -</button>
        </p>
        <p>
          <button (click)="remove($event, indx,gridster1)">remove</button>
        </p>
        <p>
          Position: {{itemComp?.item?.x}} x {{itemComp?.item?.y}}<br> Size: {{widget.w}} x {{widget.h}}
        </p>
        <pre style="position: absolute">{{ widget | json }}</pre>
      </div>

    </gridster-item>

  </gridster>
</section>`

**Comment by swiety85** [comment]
I see that you use GridsterItem options, but there is no object in your component class. Can you set itemOptions with maxWidth and maxHeight? e.g.:
```js
    itemOptions = {
        maxWidth: 3,
        maxHeight: 3
    };
```
Give me a hint if it works. If not, I will have closer look in evening.

**Comment by vistajess** [comment]
@swiety85 , Awesome, it works fine now :) 

Thank you very much!!
