### ISSUE TITLE
Auto-height for item

### ISSUE THREAD

**Issue by Pennywise83** [swiety85/angular2gridster#78]
Is it possible to set a item with auto-height attribute? In css I would set the style as "min-height: 200px", if the item content need more vertical space the height changes.
I'm looking for a good angular2 solution that can handle this scenario.

Thanks

**Comment by swiety85** [comment]
Currently it's not implemented but it's part of the [Roadmap](https://github.com/swiety85/angular2gridster/wiki/Roadmap): 
"New GridsterItem option to dynamically calculate and apply height/width of the item that the content will not have to be scrolled"

**Comment by Pennywise83** [comment]
Any update on this feature? I think it is important to use angular2gridster with a real application.

**Comment by swiety85** [comment]
Hi, sorry for late response.
I was searching one general solution to solve this issue. The main problem I got was that the scroll could be placed not directly on item inner body, but in some nested element (e.g. like in demo in `.panel-body`).
I was able to implement quick solution in my demo app by only changing `app.component.js`.
Below I listed all my changes:
```js
export class AppComponent {
    ...
    @HostListener('window:resize', ['$event'])
    onResize() {
        this.updateItemsHeight();
    }
    ngOnInit() {
        setTimeout(() => this.updateItemsHeight());
    }
    updateItemsHeight() {
        // header height - should be calculated but for demo purpose it's fixed
        const headerHeight = 37;
        this.gridster.gridster.items
            // convert each item to object with information about content height and scroll height
            .map((item) => {
                const $itemBody = item.$element.querySelector('.panel-body');

                return {
                    item,
                    scrollHeight: $itemBody ? parseInt($itemBody.scrollHeight, 10) : 0,
                    clientHeight: $itemBody ? parseInt($itemBody.clientHeight, 10) : 0
                };
            })
            // filter out items that does not have scroll (height don't have to be changed)
            .filter((data) => {
                return data.scrollHeight > data.clientHeight;
            })
            // calculate required height in lanes mount and update item "h"
            .forEach((data) => {
                data.item.h = Math.ceil(<any>((data.scrollHeight + headerHeight) / this.gridster.gridster.cellHeight));
            });
    }

    addWidget(gridster: GridsterComponent) {
        ...
        setTimeout(() => this.updateItemsHeight());
    }
    addWidgetWithoutData() {
        ...
        setTimeout(() => this.updateItemsHeight());
    }
    addWidgetFromDrag() {
        ...
        setTimeout(() => this.updateItemsHeight());
    }
```
Hopefully this will work on your component as well.
In case of any more questions, feel free to ask.

**Comment by swiety85** [comment]
This is not official feature for now, but you can find it in v1.0.0-alfa.
It’s rather half product till the moment when responsive item size will not be delivered. Then I will try to deliver some more clean and simple solution. 
For now you have to use `gridster.adjustItemsHeightToContent` like it’s described in example below. The param is optional - if you set overflow not on inner item element, then you should use selector for element inside item that is scrollable.
This solution unfortunately will not work in every case. It’s based on last child of scrollable content, so if you will have absolute element in your scrollable container that that is not the last in DOM but renders below everything, it will work as expected.
Never the less I hope that you find it useful enough.
This is an example like it would be used for demo:
```js
onReflow() {
    this.adjustItemsSize();
}
private adjustItemsSize() {
    setTimeout(() => this.gridster.adjustItemsHeightToContent(‚.panel-body’));
}
```
```html
<gridster … (reflow)="onReflow()”>…</gridster>
```
Don't hesitate to ask in case of any question.
