### ISSUE TITLE
Drag is "sticking" when gridster-item contents are scrollable

### ISSUE THREAD

**Issue by Blackbaud-XandraHarrison** [swiety85/angular2gridster#79]
I'm not sure if this is an issue with the Library or my implementation but it seems that when the gridster items have scroll-able content the drag event will continue after the mouse button is released. When this occurs, a bunch of the following warnings are thrown in the browser:

 "Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive."

This may also be related to the offset bug since this places my cursor inside the scroll-able content instead of the draggable area when I begin the drag event.

Is there a suggested fix or work around for this that anyone has seen? In the end case my content shouldn't usually be scroll-able but it would be nice to be able to counteract this behavior.

**Comment by swiety85** [comment]
Hi, which element exactly in your app has overflow property set?
I've fixed some bugs related to drag. It would be good that you also check the newest version. Maybe it's already fixed there.
I look forward for your response.

**Comment by Blackbaud-XandraHarrison** [comment]
My structure is like this:

<gridster-item>
    <div class="panel gridster-item-inner">
        <div class="panel-grabber"></div>
        <iframe></iframe>
    </div>
</gridster-item>

The iframe contains my scroll-able content, while the grabber contains an image to drag and drop the box by. I do not explicitly set the overflow property there.

**Comment by swiety85** [comment]
I would need some example. Could you create a plunker with demo or at least send html of your dashboard? It will be hard to help you if I will not fully understand a case.

**Comment by Blackbaud-XandraHarrison** [comment]
I just tried the latest version and the sticking isn't totally gone, but now when it gets stuck and you click it gets unstuck. That is good enough for me, as I am unsure if we will even have scroll-able content in the final version. If you have any thoughts on what it might be I may try a few more things but I am satisfied with this change. Thank you!

**Comment by speculees** [comment]
You can solve this by applying absolutely positioned div that is child of gridster-item and has the same dimension of a gridster-item overlaping it (z-index). This div I call "mask" appears only during the dragging process. This way the mouseup event isn't lost somewhere within the gridster-item (ex: textarea) and the problem of sticking is gone...
