### ISSUE TITLE
garbage collector

### ISSUE THREAD

**Issue by rudzikdawid** [swiety85/angular2gridster#84]
![Memory Allocation Timeline](http://i.imgur.com/zjhlclG.png)
Ending interactions with widgets  (moving, resizing) does not clear the memory

**Comment by swiety85** [comment]
I'm not an expert of tools to measure garbage collector, but as far as was able to check I did not find any problems with memory leaks. I notice that small part of memory may not be cleared on drop, but 
 starting new interaction will clear the rest of newly allocated memory from previous event.
This situation for sure does not generate any performance problems.
If you still think it's a problem, please put more clarifications.
