### ISSUE TITLE
Is there a way to reinitialize the width of the `gridster` ? 

### ISSUE THREAD

**Issue by vistajess** [swiety85/angular2gridster#85]
I have a toggable side bar and a main content on my web app. The `gridster` lies on the main content and I toggled the sidebar, the width of the `gridster` stays the same and doesn`t occupy the whole width of the main content.

**Comment by swiety85** [comment]
In closest release this problem will be solved by not setting fixed width on gridster element (in case of options.direction=vertical).
As a temporary solution you can copy gridster module to your project and remove [line 355 in gridster.service.ts](https://github.com/swiety85/angular2gridster/blob/master/src/gridster.service.ts#L355).

**Comment by vistajess** [comment]
Thanks a lot.

**Comment by swiety85** [comment]
Fixed in v 0.6.7.

**Comment by vistajess** [comment]
Thanks a lot, really appreciate it.
