### ISSUE TITLE
updateGridsterElementData() moving widget, jumping position issue

### ISSUE THREAD

**Issue by rudzikdawid** [swiety85/angular2gridster#86]
version: **0.6.5**

one of latest commits 'Update gridster element item on drag start'
**gridster.service.ts** line 196 creates the issue
```
this.gridsterComponent.updateGridsterElementData();
```
![gif issue](http://i.imgur.com/qWLSI92.gif)

The problem occurs after the scrolling of wrapper

**Comment by swiety85** [comment]
The problem already exists from very beginning. It happens only when scroll is not on window but on the wrapper element of gridster component. There is already an issue created #21. It's planned to be solved in [0.7 release](https://github.com/swiety85/angular2gridster/milestone/3).
Nevertheless thanks for info.

**Comment by rudzikdawid** [comment]
0.6.4 did not have this problem ;)

**Comment by swiety85** [comment]
Hmm.. so it's strange that it worked before. ;) Still I will fix problem in area of #21.

**Comment by swiety85** [comment]
Fix is available in v.0.6.6.
