### ISSUE TITLE
Issue with dragging widget when widgets are inside a scrollable container 

### ISSUE THREAD

**Issue by abhilashkr-tj** [swiety85/angular2gridster#87]
When the widgets are in a container which has a scroll, and then when we try to move the widgets, there is a displacement happening between the cursor and the widget. Here the main-content is the container used. Adding overflow-y:scroll to the main-content is giving me the issue. I want a scroll to the container of the widgets and not a browser scroll.

```
.main-content{
overflow-y:scroll;
max-height: 90vh;
width:100%;
}
<div class="main-content">
<!-- Gridster widget-code goes here -->
</div>
```

The same issue can be replicated in the demo page by adding the above css to the main-content of the widgets. First row scroll working fine, as you Scroll down and try drag the displacement keeps increasing between the cursor and currently dragging widget.

**Comment by swiety85** [comment]
This is already known issue: #21. Fix will be available in nearest release. Thanks for info.

**Comment by abhilashkr-tj** [comment]
Thanks . awaiting for the release :+1:

**Comment by swiety85** [comment]
Fix is available in v.0.6.6. Please check and give a hint if it works for you.
