### ISSUE TITLE
Proposed enhancement: ability to specify a fixed cell height

### ISSUE THREAD

**Issue by ghodum** [swiety85/angular2gridster#91]
I would like to propose an enhancement that would allow the developer to specify a *fixed* cell height for the grid regardless of the number of columns, width of the grid area, or cell height/width ratio. This would allow us to place content with specific height requirements on the grid as an item(s). It also allows the grid to function similar to other dashboards that I have come across.

I have implemented this locally by adding the following to GridsterService.calculateCellSize():

```
    calculateCellSize () {
        if (this.options.direction === 'horizontal') {
            // TODO: get rid of window.getComputedStyle
            this.cellHeight = Math.floor(parseFloat(window.getComputedStyle(this.gridsterComponent.$element).height) / this.options.lanes);
            this.cellWidth = this.cellHeight * this.options.widthHeightRatio;
        } else {
            // TODO: get rid of window.getComputedStyle
            this.cellWidth = Math.floor(parseFloat(window.getComputedStyle(this.gridsterComponent.$element).width) / this.options.lanes);

--->    if (this.options.cellFixedHeight) { 
                // keep a fixed cell height
--->         this.cellHeight = this.options.cellFixedHeight;
--->     } else {
                this.cellHeight = this.cellWidth / this.options.widthHeightRatio;
            }
        }
        if (this.options.heightToFontSizeRatio) {
            this._fontSize = this.cellHeight * this.options.heightToFontSizeRatio;
        }
    }
```

I can create a pull request with this change if it looks OK to include. I have not thought about a fixed cell width as that is not part of my use case, but I suppose that would be easy to add if needed.

Thanks,
Greg

**Comment by swiety85** [comment]
Good hint. This can be easily provided. I will make it work for both: vertical and horizontal direction. Should be available soon.

**Comment by swiety85** [comment]
Done in v.0.6.8. More infor in [Wiki](https://github.com/swiety85/angular2gridster/wiki/API-Documentation#gridstercomponent).

**Comment by C-odes** [comment]
Thank you for this!
