### ISSUE TITLE
Add serialization option to determine rows

### ISSUE THREAD

**Issue by Pennywise83** [swiety85/angular2gridster#92]
Hi,
is it possible to add a serialization option to determine rows? 

Actually a GridsterItem has this informations: X, Y, Width & Height. 
The original gridster had thoose options: 
data-row, data-col, data-sizex, data-sizey

Is it possible to obtain a serialized object that looks like this?
[
    {"col":1,"row":1,"size_x":2,"size_y":2},
    {"col":2,"row":4,"size_x":1,"size_y":2},
    ....
]

I need the row information becouse I need to render a gridster layout in bootstrap. I can't get the logic to obtaion the result above.

Thanks

**Comment by swiety85** [comment]
Hi, I'm not sure if I understand correctly your problem. If your data structure is like your wrote above, it's enough to connect your properties to GridsterItem component as follows:
```html
<gridster...>
  <gridster-item *ngFor="let item of items" [(x)]="item.col" [(y)]="item.row" [(w)]="item.size_x" [(h)]="item.size_y">
    ...
  </gridster-item>
</gridster>
```
GridsterItem will update passed properties (while manipulating gridster) by two way data binding, so I think serialization is not needed, because your source objects are dynamically updated.
Is this solution suitable for your problem?

**Comment by Pennywise83** [comment]
No, I need to translate the gridster layout (x,y,w,h) in a bootstrap layout.
`{
	"rows": [{
			"cols": [{
					"width": 4,
					"offset": 0
				},
				{
					"width": 6,
					"offset": 2
				}
			]
		},
		{
			"cols": [{
				"width": 12,
				"offset": 0
			}]
		}
	]
}


I'm trying to write a function but it is very tricky :(`

**Comment by swiety85** [comment]
Try this one:
```js
function toBoostrapStructure(gridsterItems, rowHeight) {
    rowHeight = rowHeight || 1;
    return { rows: gridsterItems
        .reduce((rows, item) => {
            const rowIdx = item.y / rowHeight;

            rows[rowIdx] = rows[rowIdx] || {cols: []};
            rows[rowIdx].cols.push({width: item.w, offset: item.x});

            return rows;
        }, [])
        .map((row) => {
            row.cols.sort((item1, item2) => item1.offset - item2.offset);

            return row;
        }) };
}
```
On input you can have e.g.:
```js
gridsterList = [
    {x: 0, y: 2, w: 8, h: 2},
    {x: 0, y: 0, w: 2, h: 2},
    {x: 2, y: 0, w: 4, h: 2},
    {x: 6, y: 0, w: 6, h: 2},
    {x: 8, y: 2, w: 4, h: 2}
]
```
and on output when call `toBoostrapStructure(gridsterList, 2)` you have:
```js
{
    rows: [
        { cols: [
            {"width":2,"offset":0},
            {"width":4,"offset":2},
            {"width":6,"offset":6}
        ] },
        {"cols": [
            {"width":8,"offset":0},
            {"width":4,"offset":8}
        ]}
    ]
}
```
I hope this will help you.
