### ISSUE TITLE
The result of resizing window does not work as expected

### ISSUE THREAD

**Issue by youyou098888** [swiety85/angular2gridster#94]
I have a list of `dashboardItems` with just `w`  and `h` set. the length is 2.
When I load these two items the first time, it will arrange properly. I can see the position is [0,0] and [6, 0]
However, When I resize the width of my window, I can see the `lanes` go from 12 to 6, but items go to the wrong place. Now the position is [0,0] and [0,3], But I expect them [0,0] and [3, 0];

I override the optionsChanged method like this:

      optionsChange(options: IGridsterOptions) {
        this.gridsterOptions = options;
        this.globalGridsterLanes = options.lanes;
       // here I use the new options.lanes to reset my dashboardItems's w and h
        this.dashboardItems = this.dashboardService.getGridItems(this, options.lanes);
       
     }

Do I need to do something else? @swiety85 
Any help will be appreciated, thanks.

**Comment by swiety85** [comment]
Hi, I suppose your items has width (w) 6? If yes, gridster will reposition your items for all defined breakpoints to fit the board (amount of lines), without changing their sizes.
It means that on the beginning you have 12 lanes - in this case 2 widgets * 6 widget fits 12 lanes.
When you shrink it to have only 6 lanes - only one widget fits in the row, therefore second one is placed under.
If you want items to not have different positions in different breakpoints (but only shrink widgets sizes), maybe just remove breakpoint with smaller lanes amount.

**Comment by youyou098888** [comment]
Thank you so much for your reply.
I remove the breakpoint with lanes less than 12 and it works.
But in my original case, when I shrink it from 12 lanes to 6, my items' width(w) has changed from 6 to 3 as well, I do this in the  `optionsChange` callback. I am still confused why this case can not work. @swiety85

**Comment by swiety85** [comment]
The positions of items are calculated for all breakpoints at once. This could be the reason, that it does not work for you. Angular2gridster has no support out of the box for having different sizes for different breakpoints. Never the less, I will try to provide some work around solution, if possible..

**Comment by swiety85** [comment]
The best solution for your problem is using different item widths for different breakpoints. This will be implemented in #98.
