### ISSUE TITLE
Provide support for different item width/height for different breakpoints

### ISSUE THREAD

**Issue by swiety85** [swiety85/angular2gridster#98]
Currently Gridster supports different configuration and different items position for different responsive breakpoints. There is a need to have also way to have different item sizes (#94).
One idea could be to have breakpoint prefixes for size (link with position):
* w, h
* wSm, hSm
* wMd, hMd
* wLg, hLg
* wXl, hXl

**Comment by gentle9** [comment]
I am testing this since yesterday and for now it seems to work well. Thank you for this great feature.

**Comment by yahyazini** [comment]
Any idea when will this feature be available?

Thanks.

**Comment by gentle9** [comment]
I have tested this for some days and it seems that with this feature the change event is fired for every item even if i only change one item. So if I resize one item the change event is called for every item which gives a lot of overhead.

**Comment by swiety85** [comment]
Hi, sorry for late response.  I see that this feature is really wanted.
Current merge request does not fulfill all requirements and it seems that @rudzikdawid has no time to finish it, therefore, I will try to finalize his implementation. I will try to deliver it till the end of May.

**Comment by swiety85** [comment]
I would appreciate verification if new feature works as expected. Available since v1.6.0.
